// 國小英語單字與童趣森林導師資料庫 (VocabDatabase)
const VOCAB_DATA = {
  "LIGHT": {
    word: "LIGHT",
    phonics: "/laɪt/ • L-I-G-H-T",
    zh: "光芒、點亮",
    category: "幼苗村日常",
    mascot: "foxy",
    mascotName: "小狐狸 Foxy",
    mascotImg: "assets/textures/fox-guide.png",
    dialogue: "“Look! A soft golden light dispels the morning shadows.”",
    dialogueZh: "「你看！柔和的金光驅散了清晨的陰影。」",
    prompt: "請看著銅燭台，大聲唸出：LIGHT！",
    puzzleHint: "找到古老的銅燭台，點燃它來照亮書桌角落！",
    audioFile: "assets/sounds/vocab/LIGHT.wav",
    matchKeywords: ["light", "lite", "lights", "like"],
    xp: 50,
    color: "#f6e05e"
  },
  "BOOK": {
    word: "BOOK",
    phonics: "/bʊk/ • B-O-O-K",
    zh: "書本、魔導書",
    category: "幼苗村日常",
    mascot: "foxy",
    mascotName: "小狐狸 Foxy",
    mascotImg: "assets/textures/fox-guide.png",
    dialogue: "“Open your book and discover the ancient magical words.”",
    dialogueZh: "「打開這本古老的魔導書，發現被遺忘的魔法。」",
    prompt: "請對著漂浮的古書，唸出：BOOK！",
    puzzleHint: "書桌上方的魔導書正在漂浮，裡面夾著重要之物！",
    audioFile: "assets/sounds/vocab/BOOK.wav",
    matchKeywords: ["book", "books", "look"],
    xp: 50,
    color: "#63b3ed"
  },
  "KEY": {
    word: "KEY",
    phonics: "/kiː/ • K-E-Y",
    zh: "鑰匙、關鍵",
    category: "重要道具",
    mascot: "foxy",
    mascotName: "小狐狸 Foxy",
    mascotImg: "assets/textures/fox-guide.png",
    dialogue: "“The golden key will open the locked drawer!”",
    dialogueZh: "「黃銅鑰匙能開啟緊閉的書桌抽屜！」",
    prompt: "請唸出鑰匙的真名：KEY！",
    puzzleHint: "鑰匙飄落到了桌上，用它打開抽屜！",
    audioFile: "assets/sounds/vocab/KEY.wav",
    matchKeywords: ["key", "keys", "keep", "ki"],
    xp: 50,
    color: "#ecc94b"
  },
  "RED": {
    word: "RED",
    phonics: "/red/ • R-E-D",
    zh: "紅色、火紅",
    category: "綠葉鎮魔藥",
    mascot: "bunny",
    mascotName: "小兔 Bunny",
    mascotImg: "assets/textures/rabbit-guide.png",
    dialogue: "“Red glows like a warm campfire in the forest!”",
    dialogueZh: "「紅色就像森林中溫暖的營火一樣閃閃發光！」",
    prompt: "請唸出火之魔藥的顏色：RED！",
    puzzleHint: "抽屜裡的火紅魔藥正是煉金星象儀所需的基底！",
    audioFile: "assets/sounds/vocab/RED.wav",
    matchKeywords: ["red", "read", "rad"],
    xp: 50,
    color: "#fc8181"
  },
  "BLUE": {
    word: "BLUE",
    phonics: "/bluː/ • B-L-U-E",
    zh: "藍色、蒼藍",
    category: "綠葉鎮魔藥",
    mascot: "bunny",
    mascotName: "小兔 Bunny",
    mascotImg: "assets/textures/rabbit-guide.png",
    dialogue: "“Blue is the color of the clear morning sky.”",
    dialogueZh: "「藍色是清晨晴空與清涼溪流的顏色。」",
    prompt: "請唸出水之魔藥的顏色：BLUE！",
    puzzleHint: "與 RED 藥水一起注入星象儀，喚醒星芒！",
    audioFile: "assets/sounds/vocab/BLUE.wav",
    matchKeywords: ["blue", "blew", "bloom"],
    xp: 50,
    color: "#63b3ed"
  },
  "STAR": {
    word: "STAR",
    phonics: "/stɑːr/ • S-T-A-R",
    zh: "星星、星芒",
    category: "星象秘寶",
    mascot: "bunny",
    mascotName: "小兔 Bunny",
    mascotImg: "assets/textures/rabbit-guide.png",
    dialogue: "“The bright star will guide us through the night!”",
    dialogueZh: "「明亮的星星為黑夜中的旅人指引方向！」",
    prompt: "請唸出天象儀中央閃耀的徽記：STAR！",
    puzzleHint: "調配好紅與藍藥水，星芒之石就會現身！",
    audioFile: "assets/sounds/vocab/STAR.wav",
    matchKeywords: ["star", "stars", "start"],
    xp: 70,
    color: "#f6e05e"
  },
  "CAT": {
    word: "CAT",
    phonics: "/kæt/ • C-A-T",
    zh: "貓咪",
    category: "奇幻生物",
    mascot: "mimic",
    mascotName: "貓咪寶箱怪 Mimic",
    mascotImg: "assets/textures/cute-cat-mimic.jpg",
    dialogue: "“Purr, purr... The sleepy chest with cat ears is hungry!”",
    dialogueZh: "「呼嚕呼嚕... 長著貓耳朵的小寶箱正在打盹，牠肚子餓了！」",
    prompt: "請唸出這隻可愛生物的名字：CAT！",
    puzzleHint: "角落的寶箱怪長著毛茸茸的耳朵，牠想吃新鮮的美食！",
    audioFile: "assets/sounds/vocab/CAT.wav",
    matchKeywords: ["cat", "cats", "cut"],
    xp: 50,
    color: "#ed8936"
  },
  "FISH": {
    word: "FISH",
    phonics: "/fɪʃ/ • F-I-S-H",
    zh: "魚、小魚乾",
    category: "森林美食",
    mascot: "mimic",
    mascotName: "貓咪寶箱怪 Mimic",
    mascotImg: "assets/textures/cute-cat-mimic.jpg",
    dialogue: "“Meow! A fresh fish is my favorite treat!”",
    dialogueZh: "「喵嗚！美味的小魚是我最愛的大餐！」",
    prompt: "請唸出貓咪寶箱最愛的食物：FISH！",
    puzzleHint: "把從星象台獲得的小魚乾餵給寶箱怪！",
    audioFile: "assets/sounds/vocab/FISH.wav",
    matchKeywords: ["fish", "fishes"],
    xp: 50,
    color: "#4fd1c5"
  },
  "DOOR": {
    word: "DOOR",
    phonics: "/dɔːr/ • D-O-O-R",
    zh: "大門、門扉",
    category: "大樹城遺跡",
    mascot: "ollie",
    mascotName: "貓頭鷹長老 Ollie",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Only wisdom may unlock this ancient stone door.”",
    dialogueZh: "「唯有知曉話語的真名，方能開啟遠古石門。」",
    prompt: "請唸出通往森林的出口：DOOR！",
    puzzleHint: "石門需要嵌入 STAR 與 FLOWER 魔法石！",
    audioFile: "assets/sounds/vocab/DOOR.wav",
    matchKeywords: ["door", "doors"],
    xp: 60,
    color: "#b7791f"
  },
  "FLOWER": {
    word: "FLOWER",
    phonics: "/ˈflaʊ.ər/ • F-L-O-W-E-R",
    zh: "花朵、蒼月草",
    category: "奇幻傳奇",
    mascot: "ollie",
    mascotName: "貓頭鷹長老 Ollie",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“The legendary blue flower blooms across the peaceful meadow.”",
    dialogueZh: "「傳說中的蒼月之花，正盛開在門外的整片花田上。」",
    prompt: "請唸出傳奇之花的名稱：FLOWER！",
    puzzleHint: "寶箱怪吐出的蒼月花石刻，是解開封印的關鍵！",
    audioFile: "assets/sounds/vocab/FLOWER.wav",
    matchKeywords: ["flower", "flowers", "flour"],
    xp: 80,
    color: "#63b3ed"
  },
  "OPEN": {
    word: "OPEN",
    phonics: "/ˈoʊ.pən/ • O-P-E-N",
    zh: "打開、開啟",
    category: "開門咒語",
    mascot: "ollie",
    mascotName: "貓頭鷹長老 Ollie",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Chant the spell: OPEN, and your new journey shall begin!”",
    dialogueZh: "「大聲詠唱解除封印的咒語：OPEN，迎向朝陽與花田吧！」",
    prompt: "請大聲詠唱開門真名：OPEN！",
    puzzleHint: "嵌入兩顆魔法石後，大聲唸出 OPEN 開啟石門！",
    audioFile: "assets/sounds/vocab/OPEN.wav",
    matchKeywords: ["open", "opened", "hoping"],
    xp: 70,
    color: "#48bb78"
  },
  "SUN": {
    word: "SUN",
    phonics: "/sʌn/ • S-U-N",
    zh: "太陽、朝陽",
    category: "自然天地",
    mascot: "ollie",
    mascotName: "貓頭鷹長老 Ollie",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Warm sun shines on our peaceful Whimsy Forest.”",
    dialogueZh: "「溫暖燦爛的朝陽，正照耀著和平的童趣森林。」",
    prompt: "推開門迎向陽光，唸出：SUN！",
    puzzleHint: "走出石門，步入陽光燦爛的花田！",
    audioFile: "assets/sounds/vocab/SUN.wav",
    matchKeywords: ["sun", "son", "sunny"],
    xp: 50,
    color: "#f6ad55"
  }
};
