// 國小英語單字與童趣森林導師資料庫 (VocabDatabase)
const VOCAB_DATA = {
  "LIGHT": {
    word: "LIGHT",
    phonics: "/laɪt/ • L-I-G-H-T",
    zh: "光芒、點亮",
    category: "幼苗村日常",
    mascot: "foxy",
    mascotName: "小狐狸 Foxy",
    mascotImg: "assets/textures/fox-guide.png",
    dialogue: "“Look! A soft golden light dispels the morning shadows.”",
    dialogueZh: "「你看！柔和的金光驅散了清晨的陰影。」",
    prompt: "請看著銅燭台，大聲唸出：LIGHT！",
    puzzleHint: "找到古老的銅燭台，點燃它來照亮書桌角落！",
    audioFile: "assets/sounds/vocab/LIGHT.wav",
    matchKeywords: ["light", "lite", "lights", "like"],
    xp: 50,
    color: "#f6e05e"
  },
  "BOOK": {
    word: "BOOK",
    phonics: "/bʊk/ • B-O-O-K",
    zh: "書本、魔導書",
    category: "幼苗村日常",
    mascot: "foxy",
    mascotName: "小狐狸 Foxy",
    mascotImg: "assets/textures/fox-guide.png",
    dialogue: "“Open your book and discover the ancient magical words.”",
    dialogueZh: "「打開這本古老的魔導書，發現被遺忘的魔法。」",
    prompt: "請對著漂浮的古書，唸出：BOOK！",
    puzzleHint: "書桌上方的魔導書正在漂浮，裡面夾著重要之物！",
    audioFile: "assets/sounds/vocab/BOOK.wav",
    matchKeywords: ["book", "books", "look"],
    xp: 50,
    color: "#63b3ed"
  },
  "KEY": {
    word: "KEY",
    phonics: "/kiː/ • K-E-Y",
    zh: "鑰匙、關鍵",
    category: "重要道具",
    mascot: "foxy",
    mascotName: "小狐狸 Foxy",
    mascotImg: "assets/textures/fox-guide.png",
    dialogue: "“The golden key will open the locked drawer!”",
    dialogueZh: "「黃銅鑰匙能開啟緊閉的書桌抽屜！」",
    prompt: "請唸出鑰匙的真名：KEY！",
    puzzleHint: "鑰匙飄落到了桌上，用它打開抽屜！",
    audioFile: "assets/sounds/vocab/KEY.wav",
    matchKeywords: ["key", "keys", "keep", "ki"],
    xp: 50,
    color: "#ecc94b"
  },
  "RED": {
    word: "RED",
    phonics: "/red/ • R-E-D",
    zh: "紅色、火紅",
    category: "綠葉鎮魔藥",
    mascot: "bunny",
    mascotName: "小兔 Bunny",
    mascotImg: "assets/textures/rabbit-guide.png",
    dialogue: "“Red glows like a warm campfire in the forest!”",
    dialogueZh: "「紅色就像森林中溫暖的營火一樣閃閃發光！」",
    prompt: "請唸出火之魔藥的顏色：RED！",
    puzzleHint: "抽屜裡的火紅魔藥正是煉金星象儀所需的基底！",
    audioFile: "assets/sounds/vocab/RED.wav",
    matchKeywords: ["red", "read", "rad"],
    xp: 50,
    color: "#fc8181"
  },
  "BLUE": {
    word: "BLUE",
    phonics: "/bluː/ • B-L-U-E",
    zh: "藍色、蒼藍",
    category: "綠葉鎮魔藥",
    mascot: "bunny",
    mascotName: "小兔 Bunny",
    mascotImg: "assets/textures/rabbit-guide.png",
    dialogue: "“Blue is the color of the clear morning sky.”",
    dialogueZh: "「藍色是清晨晴空與清涼溪流的顏色。」",
    prompt: "請唸出水之魔藥的顏色：BLUE！",
    puzzleHint: "與 RED 藥水一起注入星象儀，喚醒星芒！",
    audioFile: "assets/sounds/vocab/BLUE.wav",
    matchKeywords: ["blue", "blew", "bloom"],
    xp: 50,
    color: "#63b3ed"
  },
  "STAR": {
    word: "STAR",
    phonics: "/stɑːr/ • S-T-A-R",
    zh: "星星、星芒",
    category: "星象秘寶",
    mascot: "bunny",
    mascotName: "小兔 Bunny",
    mascotImg: "assets/textures/rabbit-guide.png",
    dialogue: "“The bright star will guide us through the night!”",
    dialogueZh: "「明亮的星星為黑夜中的旅人指引方向！」",
    prompt: "請唸出天象儀中央閃耀的徽記：STAR！",
    puzzleHint: "調配好紅與藍藥水，星芒之石就會現身！",
    audioFile: "assets/sounds/vocab/STAR.wav",
    matchKeywords: ["star", "stars", "start"],
    xp: 70,
    color: "#f6e05e"
  },
  "CAT": {
    word: "CAT",
    phonics: "/kæt/ • C-A-T",
    zh: "貓咪",
    category: "奇幻生物",
    mascot: "mimic",
    mascotName: "貓咪寶箱怪 Mimic",
    mascotImg: "assets/textures/cute-cat-mimic.jpg",
    dialogue: "“Purr, purr... The sleepy chest with cat ears is hungry!”",
    dialogueZh: "「呼嚕呼嚕... 長著貓耳朵的小寶箱正在打盹，牠肚子餓了！」",
    prompt: "請唸出這隻可愛生物的名字：CAT！",
    puzzleHint: "角落的寶箱怪長著毛茸茸的耳朵，牠想吃新鮮的美食！",
    audioFile: "assets/sounds/vocab/CAT.wav",
    matchKeywords: ["cat", "cats", "cut"],
    xp: 50,
    color: "#ed8936"
  },
  "FISH": {
    word: "FISH",
    phonics: "/fɪʃ/ • F-I-S-H",
    zh: "魚、小魚乾",
    category: "森林美食",
    mascot: "mimic",
    mascotName: "貓咪寶箱怪 Mimic",
    mascotImg: "assets/textures/cute-cat-mimic.jpg",
    dialogue: "“Meow! A fresh fish is my favorite treat!”",
    dialogueZh: "「喵嗚！美味的小魚是我最愛的大餐！」",
    prompt: "請唸出貓咪寶箱最愛的食物：FISH！",
    puzzleHint: "把從星象台獲得的小魚乾餵給寶箱怪！",
    audioFile: "assets/sounds/vocab/FISH.wav",
    matchKeywords: ["fish", "fishes"],
    xp: 50,
    color: "#4fd1c5"
  },
  "DOOR": {
    word: "DOOR",
    phonics: "/dɔːr/ • D-O-O-R",
    zh: "大門、門扉",
    category: "大樹城遺跡",
    mascot: "ollie",
    mascotName: "貓頭鷹長老 Ollie",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Only wisdom may unlock this ancient stone door.”",
    dialogueZh: "「唯有知曉話語的真名，方能開啟遠古石門。」",
    prompt: "請唸出通往森林的出口：DOOR！",
    puzzleHint: "石門需要嵌入 STAR 與 FLOWER 魔法石！",
    audioFile: "assets/sounds/vocab/DOOR.wav",
    matchKeywords: ["door", "doors"],
    xp: 60,
    color: "#b7791f"
  },
  "FLOWER": {
    word: "FLOWER",
    phonics: "/ˈflaʊ.ər/ • F-L-O-W-E-R",
    zh: "花朵、蒼月草",
    category: "奇幻傳奇",
    mascot: "ollie",
    mascotName: "貓頭鷹長老 Ollie",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“The legendary blue flower blooms across the peaceful meadow.”",
    dialogueZh: "「傳說中的蒼月之花，正盛開在門外的整片花田上。」",
    prompt: "請唸出傳奇之花的名稱：FLOWER！",
    puzzleHint: "寶箱怪吐出的蒼月花石刻，是解開封印的關鍵！",
    audioFile: "assets/sounds/vocab/FLOWER.wav",
    matchKeywords: ["flower", "flowers", "flour"],
    xp: 80,
    color: "#63b3ed"
  },
  "OPEN": {
    word: "OPEN",
    phonics: "/ˈoʊ.pən/ • O-P-E-N",
    zh: "打開、開啟",
    category: "開門咒語",
    mascot: "ollie",
    mascotName: "貓頭鷹長老 Ollie",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Chant the spell: OPEN, and your new journey shall begin!”",
    dialogueZh: "「大聲詠唱解除封印的咒語：OPEN，迎向朝陽與花田吧！」",
    prompt: "請大聲詠唱開門真名：OPEN！",
    puzzleHint: "嵌入兩顆魔法石後，大聲唸出 OPEN 開啟石門！",
    audioFile: "assets/sounds/vocab/OPEN.wav",
    matchKeywords: ["open", "opened", "hoping"],
    xp: 70,
    color: "#48bb78"
  },
  "SUN": {
    word: "SUN",
    phonics: "/sʌn/ • S-U-N",
    zh: "太陽、朝陽",
    category: "自然天地",
    mascot: "ollie",
    mascotName: "貓頭鷹長老 Ollie",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Warm sun shines on our peaceful Whimsy Forest.”",
    dialogueZh: "「溫暖燦爛的朝陽，正照耀著和平的童趣森林。」",
    prompt: "推開門迎向陽光，唸出：SUN！",
    puzzleHint: "走出石門，步入陽光燦爛的花田！",
    audioFile: "assets/sounds/vocab/SUN.wav",
    matchKeywords: ["sun", "son", "sunny"],
    xp: 50,
    color: "#f6ad55"
  },
  "SHIP": {
    word: "SHIP",
    phonics: "/ʃɪp/ • S-H-I-P",
    zh: "大帆船、輪船",
    category: "蔚藍秘境海港",
    mascot: "marina",
    mascotName: "瑪琳娜船長 Marina",
    mascotImg: "assets/textures/tex-town-facade.jpg",
    dialogue: "“The majestic galleon ship is ready to set sail across the ocean!”",
    dialogueZh: "「威風凜凜的三桅大帆船已備妥風帆，準備啟航橫越大洋！」",
    prompt: "請看著碼頭旁停泊的宏偉帆船，唸出：SHIP！",
    puzzleHint: "碼頭停泊著巨大的三桅遠洋帆船，登上甲板感受航海的壯麗！",
    audioFile: "assets/sounds/vocab/SHIP.wav",
    matchKeywords: ["ship", "ships", "sheep"],
    xp: 60,
    color: "#0284c7"
  },
  "BOAT": {
    word: "BOAT",
    phonics: "/boʊt/ • B-O-A-T",
    zh: "小艇、小木船",
    category: "蔚藍秘境海港",
    mascot: "marina",
    mascotName: "瑪琳娜船長 Marina",
    mascotImg: "assets/textures/tex-town-facade.jpg",
    dialogue: "“The wooden boat rocks gently beside the harbor pier.”",
    dialogueZh: "「繫在碼頭邊的木造小艇隨著海浪輕輕搖曳晃動。」",
    prompt: "請看著碼頭繫纜樁旁的小船，唸出：BOAT！",
    puzzleHint: "港口木棧道邊繫著一艘輕巧的小木艇，是近海探險的良伴！",
    audioFile: "assets/sounds/vocab/BOAT.wav",
    matchKeywords: ["boat", "boats", "bolt"],
    xp: 50,
    color: "#f59e0b"
  },
  "WIND": {
    word: "WIND",
    phonics: "/wɪnd/ • W-I-N-D",
    zh: "微風、航海之風",
    category: "蔚藍秘境海港",
    mascot: "marina",
    mascotName: "瑪琳娜船長 Marina",
    mascotImg: "assets/textures/tex-town-facade.jpg",
    dialogue: "“A brisk ocean wind fills the sails and turns the lighthouse vane!”",
    dialogueZh: "「強勁清爽的海風吹鼓了風帆，也轉動了燈塔上的航海風向標！」",
    prompt: "請感受吹拂海面的清爽微風，唸出：WIND！",
    puzzleHint: "燈塔頂端的風向標與風向旗正隨風旋轉，為水手測量風向！",
    audioFile: "assets/sounds/vocab/WIND.wav",
    matchKeywords: ["wind", "winds", "win", "wing"],
    xp: 50,
    color: "#38bdf8"
  },
  "WATER": {
    word: "WATER",
    phonics: "/ˈwɔː.tər/ • W-A-T-E-R",
    zh: "海水、碧波清泉",
    category: "蔚藍秘境海港",
    mascot: "marina",
    mascotName: "瑪琳娜船長 Marina",
    mascotImg: "assets/textures/tex-town-facade.jpg",
    dialogue: "“The crystal clear blue water sparkles under the warm morning sunlight.”",
    dialogueZh: "「澄澈湛藍的港灣海水在晨曦朝陽下閃爍著點點波光。」",
    prompt: "請俯瞰碼頭邊清澈碧藍的海水，唸出：WATER！",
    puzzleHint: "碼頭觀景台邊的海水碧藍透亮，波光粼粼！",
    audioFile: "assets/sounds/vocab/WATER.wav",
    matchKeywords: ["water", "waters", "waiter"],
    xp: 50,
    color: "#06b6d4"
  },
  "MOON": {
    word: "MOON",
    phonics: "/muːn/ • M-O-O-N",
    zh: "月亮、蒼月",
    category: "雲頂星空觀測站",
    mascot: "aethel",
    mascotName: "艾瑟爾賢者 Aethel",
    mascotImg: "assets/textures/tex-clocktower-face.jpg",
    dialogue: "“Look up! The silvery crescent moon watches over our magical academy.”",
    dialogueZh: "「抬頭看！銀白色的弦月正在雲頂天幕守護著我們的魔法學院。」",
    prompt: "請看著觀測站的蒼月潮汐日晷儀，唸出：MOON！",
    puzzleHint: "觀測站中央的潮汐日晷正隨著月相緩緩旋轉，散發出銀藍光芒！",
    audioFile: "assets/sounds/vocab/MOON.wav",
    matchKeywords: ["moon", "moons", "mood"],
    xp: 60,
    color: "#93c5fd"
  },
  "CLOUD": {
    word: "CLOUD",
    phonics: "/klaʊd/ • C-L-O-U-D",
    zh: "雲朵、雲海",
    category: "雲頂星空觀測站",
    mascot: "aethel",
    mascotName: "艾瑟爾賢者 Aethel",
    mascotImg: "assets/textures/tex-clocktower-face.jpg",
    dialogue: "“Fluffy white clouds float peacefully like an ocean beneath our feet.”",
    dialogueZh: "「綿密蓬鬆的白色雲朵就像腳下一望無際的雲海，靜靜飄動。」",
    prompt: "請俯瞰觀星露台邊緣起伏的雲海，唸出：CLOUD！",
    puzzleHint: "觀景浮台四周翻湧著純白的立體雲海，踩上去彷彿漫步空中！",
    audioFile: "assets/sounds/vocab/CLOUD.wav",
    matchKeywords: ["cloud", "clouds", "clown", "crowd"],
    xp: 50,
    color: "#e2e8f0"
  },
  "SKY": {
    word: "SKY",
    phonics: "/skaɪ/ • S-K-Y",
    zh: "天空、星空蒼穹",
    category: "雲頂星空觀測站",
    mascot: "aethel",
    mascotName: "艾瑟爾賢者 Aethel",
    mascotImg: "assets/textures/tex-clocktower-face.jpg",
    dialogue: "“The endless night sky is filled with glowing stars and distant galaxies!”",
    dialogueZh: "「無垠的夜空蒼穹中點綴著閃耀的恆星與遙遠星系！」",
    prompt: "請透過巨型天文望遠鏡望向無垠夜空，唸出：SKY！",
    puzzleHint: "巨型折射望遠鏡正指向天頂星河，窺探浩瀚宇宙的奧秘！",
    audioFile: "assets/sounds/vocab/SKY.wav",
    matchKeywords: ["sky", "skies", "ski"],
    xp: 50,
    color: "#38bdf8"
  },
  "SNOW": {
    word: "SNOW",
    phonics: "/snoʊ/ • S-N-O-W",
    zh: "雪、積雪、下雪",
    category: "極光冰雪聖域",
    mascot: "frost",
    mascotName: "佛洛斯特長老 Frost",
    mascotImg: "assets/textures/tex-clocktower-face.jpg",
    dialogue: "“Pure white snow is gently falling from the shimmering aurora sky!”",
    dialogueZh: "「純白的雪花正從閃爍的極光天幕中輕盈飄落！」",
    prompt: "請看著旋轉的冰雪結晶風向儀，唸出：SNOW！",
    puzzleHint: "六角萬年雪花結晶正隨著極光微風旋轉，散發出冰藍光芒！",
    audioFile: "assets/sounds/vocab/SNOW.wav",
    matchKeywords: ["snow", "snows", "slow", "no"],
    xp: 50,
    color: "#e0f2fe"
  },
  "COLD": {
    word: "COLD",
    phonics: "/koʊld/ • C-O-L-D",
    zh: "寒冷的、冰涼的",
    category: "極光冰雪聖域",
    mascot: "frost",
    mascotName: "佛洛斯特長老 Frost",
    mascotImg: "assets/textures/tex-clocktower-face.jpg",
    dialogue: "“Brrr! The arctic frost wind is very cold, but your spirit is brave!”",
    dialogueZh: "「呼！極地的寒風雖然非常寒冷，但你的冒險意志十分堅定！」",
    prompt: "請觸碰刻有寒霜符文的極寒方尖碑，唸出：COLD！",
    puzzleHint: "晶透的萬年玄冰方尖碑正散發陣陣寒氣冷霧，凍結了四周的時間！",
    audioFile: "assets/sounds/vocab/COLD.wav",
    matchKeywords: ["cold", "colds", "call", "hold", "gold"],
    xp: 50,
    color: "#38bdf8"
  },
  "WINTER": {
    word: "WINTER",
    phonics: "/ˈwɪn.tər/ • W-I-N-T-E-R",
    zh: "冬天、冬季",
    category: "極光冰雪聖域",
    mascot: "frost",
    mascotName: "佛洛斯特長老 Frost",
    mascotImg: "assets/textures/tex-clocktower-face.jpg",
    dialogue: "“Winter brings peaceful white blankets and magical sparkling icicles.”",
    dialogueZh: "「冬天為神峰披上了平靜的白雪毛毯，掛滿了奇幻的晶瑩冰錐。」",
    prompt: "請仰望披上雪毯的冬之常青松，唸出：WINTER！",
    puzzleHint: "傲雪挺立的冬之常青松上垂掛著晶瑩冰柱與溫暖冬燈！",
    audioFile: "assets/sounds/vocab/WINTER.wav",
    matchKeywords: ["winter", "winters", "winner", "wind"],
    xp: 60,
    color: "#93c5fd"
  },
  "WHITE": {
    word: "WHITE",
    phonics: "/waɪt/ • W-H-I-T-E",
    zh: "白色的、純白",
    category: "極光冰雪聖域",
    mascot: "frost",
    mascotName: "佛洛斯特長老 Frost",
    mascotImg: "assets/textures/tex-clocktower-face.jpg",
    dialogue: "“The snowman guardian wears a soft blue scarf over his white coat!”",
    dialogueZh: "「純白的雪人守護者在他的白衣上繫了一條溫暖的藍色圍巾！」",
    prompt: "請對著戴單片眼鏡的雪境守護者，唸出：WHITE！",
    puzzleHint: "圓滾滾的純白雪人正俏皮地向你眨眼，守護著冰雪聖殿！",
    audioFile: "assets/sounds/vocab/WHITE.wav",
    matchKeywords: ["white", "whites", "why", "wait"],
    xp: 50,
    color: "#f8fafc"
  },
  "WARM": {
    word: "WARM",
    phonics: "/wɔːrm/ • W-A-R-M",
    zh: "溫暖的、暖和的",
    category: "極光冰雪聖域",
    mascot: "frost",
    mascotName: "佛洛斯特長老 Frost",
    mascotImg: "assets/textures/tex-clocktower-face.jpg",
    dialogue: "“Come close to the magic hearth. Its glowing fire keeps us warm and safe.”",
    dialogueZh: "「靠近這座極光暖心魔爐吧，它跳動的金色暖焰讓我們溫暖又安全。」",
    prompt: "請伸手靠近跳動金焰的極光魔爐，唸出：WARM！",
    puzzleHint: "在冰天雪地中燃燒著永不熄滅的暖心魔火，驅散了刺骨寒氣！",
    audioFile: "assets/sounds/vocab/WARM.wav",
    matchKeywords: ["warm", "warms", "worm", "wall"],
    xp: 60,
    color: "#fbbf24"
  },
  "CLIMB": {
    word: "CLIMB",
    phonics: "/klaɪm/ • C-L-I-M-B",
    zh: "攀登、攀爬",
    category: "極光冰雪聖域",
    mascot: "frost",
    mascotName: "佛洛斯特長老 Frost",
    mascotImg: "assets/textures/tex-clocktower-face.jpg",
    dialogue: "“Brave hero, climb the frosted steps to reach the highest peak of magic!”",
    dialogueZh: "「勇敢的英雄，攀登這座寒霜冰階，抵達魔法大陸至高無上的頂峰！」",
    prompt: "請踏上通往聖域極光之巔的旋轉冰階，唸出：CLIMB！",
    puzzleHint: "旋轉上升的晶瑩冰階穿透雲霄，攀登上去即可啟程前往大魔導士殿堂！",
    audioFile: "assets/sounds/vocab/CLIMB.wav",
    matchKeywords: ["climb", "climbs", "climbed", "climate", "line"],
    xp: 70,
    color: "#a855f7"
  },
  "LIBRARY": {
    word: "LIBRARY",
    phonics: "/ˈlaɪ.brer.i/ • L-I-B-R-A-R-Y",
    zh: "圖書館、藏書閣",
    category: "星界萬神殿堂",
    mascot: "oliver",
    mascotName: "奧利弗大校長 Oliver",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Welcome to the Astral Library, where thousands of magical grimoires rest quietly.”",
    dialogueZh: "「歡迎來到星界智慧大圖書館，成千上萬的魔法萬卷古籍在此靜靜守護智慧。」",
    prompt: "請走向雙層紫檀木智慧大書閣，唸出：LIBRARY！",
    puzzleHint: "宏偉的大理石書閣典藏著古往今來的宇宙奧秘，書架散發微光！",
    audioFile: "assets/sounds/vocab/LIBRARY.wav",
    matchKeywords: ["library", "libraries", "berry", "liberty"],
    xp: 60,
    color: "#6366f1"
  },
  "READ": {
    word: "READ",
    phonics: "/riːd/ • R-E-A-D",
    zh: "閱讀、朗讀",
    category: "星界萬神殿堂",
    mascot: "oliver",
    mascotName: "奧利弗大校長 Oliver",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Read the ancient floating grimoire to illuminate your path through the stars.”",
    dialogueZh: "「閱讀這本遠古懸浮魔法大典，讓智慧的光芒照亮你穿行星海的旅途。」",
    prompt: "請翻閱講台上懸浮發光的遠古大典，唸出：READ！",
    puzzleHint: "講台上的神聖法典正自動懸浮翻動，星光符文從字裡行間飄散而出！",
    audioFile: "assets/sounds/vocab/READ.wav",
    matchKeywords: ["read", "reads", "reader", "reading", "red"],
    xp: 50,
    color: "#818cf8"
  },
  "WRITE": {
    word: "WRITE",
    phonics: "/raɪt/ • W-R-I-T-E",
    zh: "書寫、筆耕",
    category: "星界萬神殿堂",
    mascot: "oliver",
    mascotName: "奧利弗大校長 Oliver",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Take up the golden quill and write your own legend in the Book of Stars.”",
    dialogueZh: "「拿起這支黃金羽毛筆，在星辰之書上親手寫下屬於你的英雄傳奇吧。」",
    prompt: "請在黑曜石書寫桌前提起金色羽毛筆，唸出：WRITE！",
    puzzleHint: "黑曜石書桌上擺放著金色孔雀羽毛筆與古老羊皮紙，等待你寫下智慧之語！",
    audioFile: "assets/sounds/vocab/WRITE.wav",
    matchKeywords: ["write", "writes", "writer", "right", "white"],
    xp: 50,
    color: "#f59e0b"
  },
  "THINK": {
    word: "THINK",
    phonics: "/θɪŋk/ • T-H-I-N-K",
    zh: "思考、沉思",
    category: "星界萬神殿堂",
    mascot: "oliver",
    mascotName: "奧利弗大校長 Oliver",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Quiet your mind and think deeply by the sacred pool of reflection.”",
    dialogueZh: "「平靜你的心靈，在沉思之泉旁深度思考，真正的洞察力來自冷靜的思維。」",
    prompt: "請凝望八角白玉沉思之泉的水中星芒，唸出：THINK！",
    puzzleHint: "澄澈的白玉泉水倒映著浩瀚宇宙，池心的水晶稜鏡緩緩自轉啟迪思緒！",
    audioFile: "assets/sounds/vocab/THINK.wav",
    matchKeywords: ["think", "thinks", "thinking", "thank", "thin"],
    xp: 60,
    color: "#38bdf8"
  },
  "SMART": {
    word: "SMART",
    phonics: "/smɑːrt/ • S-M-A-R-T",
    zh: "聰明的、智慧的",
    category: "星界萬神殿堂",
    mascot: "oliver",
    mascotName: "奧利弗大校長 Oliver",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Knowledge and curiosity make every young adventurer smart and wise.”",
    dialogueZh: "「對世界的好奇與知識的累積，能讓每一位年輕冒險者變得無比聰明與睿智。」",
    prompt: "請注視衡量知識平衡的黃金天秤儀，唸出：SMART！",
    puzzleHint: "青銅與黃金鑄造的天秤儀左端托著智慧金腦，右端托著璀璨星石！",
    audioFile: "assets/sounds/vocab/SMART.wav",
    matchKeywords: ["smart", "smarts", "start", "small", "art"],
    xp: 60,
    color: "#fde047"
  },
  "FLY": {
    word: "FLY",
    phonics: "/flaɪ/ • F-L-Y",
    zh: "飛翔、展翅高飛",
    category: "星界萬神殿堂",
    mascot: "oliver",
    mascotName: "奧利弗大校長 Oliver",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Spread your wings of wisdom and fly high above the boundless celestial sky!”",
    dialogueZh: "「展開你的智慧之翼，在無邊無際的星界蒼穹中自在飛翔、傲視天際！」",
    prompt: "請登上兩側佇立金鷹雕像的白玉展翅天台，唸出：FLY！",
    puzzleHint: "展翅天台的中央懸浮著巨大的金色光翼光環，踏上去即可展翅飛翔！",
    audioFile: "assets/sounds/vocab/FLY.wav",
    matchKeywords: ["fly", "flies", "flying", "flew", "light"],
    xp: 70,
    color: "#c084fc"
  },
  "ISLAND": {
    word: "ISLAND",
    phonics: "/ˈaɪ.lənd/ • I-S-L-A-N-D",
    zh: "島嶼、浮空仙島",
    category: "蒼穹虹光空島",
    mascot: "aria",
    mascotName: "艾莉雅 Aria",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Welcome to the Celestial Sky Island, floating freely high above the sea of clouds!”",
    dialogueZh: "「歡迎來到蒼穹浮空仙島！這座神聖空島自由自在地懸浮在無垠九天雲海之上！」",
    prompt: "請邁步登上這座懸浮於雲端的翡翠空島，唸出：ISLAND！",
    puzzleHint: "懸浮於九天雲海之上的翡翠仙島，四周流轉著輕柔的微風與祥雲！",
    audioFile: "assets/sounds/vocab/ISLAND.wav",
    matchKeywords: ["island", "islands", "eye", "land", "highland"],
    xp: 60,
    color: "#38bdf8"
  },
  "RAINBOW": {
    word: "RAINBOW",
    phonics: "/ˈreɪn.boʊ/ • R-A-I-N-B-O-W",
    zh: "彩虹、虹霓天橋",
    category: "蒼穹虹光空島",
    mascot: "aria",
    mascotName: "艾莉雅 Aria",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Walk across the shining rainbow bridge to connect your dreams with the infinite sky.”",
    dialogueZh: "「走過這座璀璨的彩虹天橋，讓七彩光芒將你的夢想與無垠蒼穹相連。」",
    prompt: "請踏上橫跨島嶼間的七彩虹霓以太天橋，唸出：RAINBOW！",
    puzzleHint: "橫跨空島的半透明天橋流動著赤橙黃綠青藍紫七重光芒，如夢似幻！",
    audioFile: "assets/sounds/vocab/RAINBOW.wav",
    matchKeywords: ["rainbow", "rainbows", "rain", "bow", "bows"],
    xp: 60,
    color: "#f43f5e"
  },
  "MUSIC": {
    word: "MUSIC",
    phonics: "/ˈmjuː.zɪk/ • M-U-S-I-C",
    zh: "音樂、天籟樂曲",
    category: "蒼穹虹光空島",
    mascot: "aria",
    mascotName: "艾莉雅 Aria",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Listen to the celestial music played by the starry wind and crystalline keys.”",
    dialogueZh: "「聆聽這由星風與水晶琴鍵彈奏出的天界天籟音樂，它是撫慰心靈的奇蹟。」",
    prompt: "請撫過浮空涼亭中的天籟水晶星琴，唸出：MUSIC！",
    puzzleHint: "水晶鋼琴上的琴鍵自行跳躍律動，五線譜光環正飄揚在半空中！",
    audioFile: "assets/sounds/vocab/MUSIC.wav",
    matchKeywords: ["music", "musics", "muse", "musical", "amuse"],
    xp: 60,
    color: "#a855f7"
  },
  "SING": {
    word: "SING",
    phonics: "/sɪŋ/ • S-I-N-G",
    zh: "唱歌、歌詠詠唱",
    category: "蒼穹虹光空島",
    mascot: "aria",
    mascotName: "艾莉雅 Aria",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Let your joyful voice soar! Sing like the sapphire skybird welcoming the dawn.”",
    dialogueZh: "「讓歡欣的歌聲扶搖直上！如同天青靈鳥迎接破曉晨曦般盡情高歌吧！」",
    prompt: "請走近天青靈鳥棲息的歌詠鳥居，唸出：SING！",
    puzzleHint: "展翅的天青靈鳥在金色鳥居上振翅清啼，金色音符粒子如雨般灑落！",
    audioFile: "assets/sounds/vocab/SING.wav",
    matchKeywords: ["sing", "sings", "singer", "singing", "song", "thing"],
    xp: 60,
    color: "#06b6d4"
  },
  "DANCE": {
    word: "DANCE",
    phonics: "/dæns/ • D-A-N-C-E",
    zh: "跳舞、翩翩起舞",
    category: "蒼穹虹光空島",
    mascot: "aria",
    mascotName: "艾莉雅 Aria",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Step onto the starlight quartz floor and dance to the rhythm of the floating islands.”",
    dialogueZh: "「踏上星光石英舞池，跟隨空島的旋律翩翩起舞，每一步都能綻放出絢爛光芒。」",
    prompt: "請踏上中央環形星光石英律動舞池，唸出：DANCE！",
    puzzleHint: "環狀石英舞池的音階踏板踩下時會發出清脆的八音盒聲響與七彩光環！",
    audioFile: "assets/sounds/vocab/DANCE.wav",
    matchKeywords: ["dance", "dances", "dancer", "dancing", "danced"],
    xp: 60,
    color: "#10b981"
  },
  "DREAM": {
    word: "DREAM",
    phonics: "/driːm/ • D-R-E-A-M",
    zh: "夢想、美夢、許願",
    category: "蒼穹虹光空島",
    mascot: "aria",
    mascotName: "艾莉雅 Aria",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Every grand achievement begins with a dream. Hold tight to your dreams and conquer the future!”",
    dialogueZh: "「所有偉大的成就都始於一個勇敢的夢想。緊握你的夢想，展翅開拓未來吧！」",
    prompt: "請在空島巔峰的祈願星泉前許下願望，唸出：DREAM！",
    puzzleHint: "八角星光祈願天池向虛空傾瀉成落雲瀑布，水面泛起璀璨星光，在此許願夢想成真！",
    audioFile: "assets/sounds/vocab/DREAM.wav",
    matchKeywords: ["dream", "dreams", "dreamer", "dreaming", "team"],
    xp: 70,
    color: "#fbbf24"
  }
};

// 關卡主英語問句試煉題庫 (Guardian Question Trials Database)
// 每位關卡主具備：
// 1. NPC 開場對話
// 2. 兩道英語問句填充選擇題 (Multiple Choice)
// 3. 一道高階英語問句朗讀挑戰 (Sentence Speech Trial, 正確率 >= 80%)
const GUARDIAN_TRIALS = {
  'zone6': {
    zoneId: 'zone6',
    zoneName: '蔚藍秘境海港',
    bossId: 'captain_marina',
    bossName: '瑪琳娜船長 (Captain Marina)',
    bossRole: '⚓ 皇家海港總督・傳奇領航者',
    bossAvatar: 'assets/textures/tex-town-facade.jpg',
    bossEmoji: '⚓',
    introDialogue: "Ahoy! 勇敢的冒險者！你已經掌握了海港的所有基礎字彙。但是，想要拿到航向未知海域的通行證並獲得本關卡【海港守護之星】，你必須通過我的「英語問句三重試煉」！拔錨啟航，接受挑戰吧！",
    rewardXP: 200,
    starName: "海港守護之星 ⚓",
    victoryDialogue: "Bravo! 你的英語問句掌握得無懈可擊，發音精準有力！以皇家海港總督之名，我將這顆【海港守護之星】授予你，浩瀚的星海航道已為你敞開！",
    questions: [
      {
        stage: 1,
        type: 'choice',
        title: '問句試煉 1/3：疑問詞選擇題 (Question Words)',
        scenario: '航海探索情境：你在碼頭想打聽遠洋帆船的航行方向',
        prompt: '請問句中的空格應填入哪一個疑問詞？',
        sentence: "“_____ is the big ship sailing to?”",
        sentenceZh: "「這艘大帆船要航向哪裡？」",
        audioText: "Where is the big ship sailing to?",
        options: [
          { key: 'A', text: 'Where', correct: true, hint: '答對了！詢問「地點/目的地」使用 Where。' },
          { key: 'B', text: 'When', correct: false, hint: 'When 是詢問「時間」，這裡詢問的是航向哪裡喔！' },
          { key: 'C', text: 'Who', correct: false, hint: 'Who 是詢問「人物」，不能用來問航行目的地喔！' },
          { key: 'D', text: 'What', correct: false, hint: '詢問航向某個目的地，以「Where ... sailing to?」最道地！' }
        ],
        explanation: '【Where】用於詢問地點、場所與目的地。「Where is the big ship sailing to?」意思為「這艘大帆船要航向何處？」。'
      },
      {
        stage: 2,
        type: 'choice',
        title: '問句試煉 2/3：情境助動詞選擇題 (Auxiliary Verbs)',
        scenario: '航海導航情境：船長指著遠方海平面的燈塔光芒詢問隊員',
        prompt: '請問句中的空格應填入哪一個助動詞？',
        sentence: "“_____ you see the lighthouse beam across the sea?”",
        sentenceZh: "「你能看見橫越海面的燈塔光束嗎？」",
        audioText: "Can you see the lighthouse beam across the sea?",
        options: [
          { key: 'A', text: 'Can', correct: true, hint: '太厲害了！Can you see... 用於詢問「你能看見...嗎？」。' },
          { key: 'B', text: 'Is', correct: false, hint: '主詞是 you 且搭配動詞原形 see，不能使用 Is 喔！' },
          { key: 'C', text: 'Does', correct: false, hint: '主詞是 you，一般動詞現在式疑問要用 Do 而非 Does。' },
          { key: 'D', text: 'Are', correct: false, hint: 'Are you 後方需接 V-ing 或形容詞，接原形動詞 see 需使用 Can。' }
        ],
        explanation: '【Can】表示能力或感官觀察，「Can you see...?」為生活與航海中最常用的詢問句：「你能看見...嗎？」。'
      },
      {
        stage: 3,
        type: 'speech',
        title: '終極試煉 3/3：英語問句口說朗讀 (Required Accuracy ≥ 80%)',
        scenario: '海港尋路任務：請用清晰標準的英語問句，向海港水手詢問燈塔的方位！',
        prompt: '請點擊下方麥克風，完整清晰地朗讀出這句英語問句：',
        targetSentence: "Where is the harbor lighthouse?",
        targetSentenceZh: "「請問海港燈塔在哪裡？」",
        phoneticGuide: "/wɛər ɪz ðə ˈhɑːrbər ˈlaɪtˌhaʊs/",
        targetKeywords: ["where", "is", "the", "harbor", "lighthouse"],
        requiredAccuracy: 80,
        audioText: "Where is the harbor lighthouse?"
      }
    ]
  },
  'zone1': {
    zoneId: 'zone1',
    zoneName: '見習學徒書齋',
    bossId: 'elder_ollie',
    bossName: '貓頭鷹長老 Ollie (Elder Ollie)',
    bossRole: '🦉 智慧殿堂守護者・貓頭鷹長老',
    bossAvatar: 'assets/textures/owl-guide.png',
    bossEmoji: '🦉',
    introDialogue: "咕咕！年輕的魔法學徒，你在書齋中的學習非常出色。不過，真正的大學者必須能夠靈活使用英語問句發問！來吧，通過我的問句三重考驗，奪取【書齋守護之星】！",
    rewardXP: 150,
    starName: "書齋守護之星 📜",
    victoryDialogue: "智慧的光芒在你眼中閃耀！你的英語問句精準無誤，這是屬於你的【書齋守護之星】！",
    questions: [
      {
        stage: 1,
        type: 'choice',
        title: '問句試煉 1/3：疑問詞選擇題 (Question Words)',
        scenario: '書齋探秘情境：你想知道桌上這本古老魔導書的名稱或內容',
        prompt: '請問句中的空格應填入哪一個疑問詞？',
        sentence: "“_____ is this magic book about?”",
        sentenceZh: "「這本魔法書是關於什麼的？」",
        audioText: "What is this magic book about?",
        options: [
          { key: 'A', text: 'What', correct: true, hint: '正確！詢問「事物內容」使用 What。' },
          { key: 'B', text: 'Where', correct: false, hint: 'Where 是詢問「地點」，詢問內容要用 What。' },
          { key: 'C', text: 'Who', correct: false, hint: 'Who 是詢問「人物」喔！' },
          { key: 'D', text: 'When', correct: false, hint: 'When 是詢問「時間」喔！' }
        ],
        explanation: '【What】用於詢問事物內容，「What is this magic book about?」意為「這本魔法書是關於什麼的？」。'
      },
      {
        stage: 2,
        type: 'choice',
        title: '問句試煉 2/3：位置問句選擇題 (Where & Prepositions)',
        scenario: '尋找關鍵道具：你在書齋中尋找打開抽屜的黃金鑰匙',
        prompt: '請問句中的空格應填入哪一個疑問詞？',
        sentence: "“_____ is the golden key on the desk?”",
        sentenceZh: "「書桌上的那把黃金鑰匙在哪裡？」",
        audioText: "Where is the golden key on the desk?",
        options: [
          { key: 'A', text: 'Where', correct: true, hint: '太棒了！詢問「在哪裡」要用 Where！' },
          { key: 'B', text: 'How', correct: false, hint: 'How 是詢問「如何/方式」喔。' },
          { key: 'C', text: 'Why', correct: false, hint: 'Why 是詢問「原因」喔。' },
          { key: 'D', text: 'Which', correct: false, hint: '這裡已明確指特定金鑰匙，詢問位置用 Where 最合適。' }
        ],
        explanation: '【Where】用於詢問位置或場所，「Where is the golden key on the desk?」意為「書桌上的黃金鑰匙在哪裡？」。'
      },
      {
        stage: 3,
        type: 'speech',
        title: '終極試煉 3/3：英語問句口說朗讀 (Required Accuracy ≥ 80%)',
        scenario: '書齋問答挑戰：請清晰標準朗讀出詢問光芒與燭台的問句！',
        prompt: '請點擊下方麥克風，完整清晰地朗讀出這句英語問句：',
        targetSentence: "Can you see the golden light?",
        targetSentenceZh: "「你能看見那道金色光芒嗎？」",
        phoneticGuide: "/kæn juː siː ðə ˈɡoʊldən laɪt/",
        targetKeywords: ["can", "you", "see", "the", "golden", "light"],
        requiredAccuracy: 80,
        audioText: "Can you see the golden light?"
      }
    ]
  },
  'zone7': {
    zoneId: 'zone7',
    zoneName: '雲頂星空觀測站',
    bossId: 'astrologer_aethel',
    bossName: '艾瑟爾賢者 (Astrologer Aethel)',
    bossRole: '🔭 星象總監・蒼穹觀星大師',
    bossAvatar: 'assets/textures/tex-clocktower-face.jpg',
    bossEmoji: '🔭',
    introDialogue: "Greetings, 年輕的尋星使者！我是雲頂星空觀測站的守護者——艾瑟爾 🔭。你已經攀登至學院最高的蒼穹之巔，掌握了星空的核心詞彙。想要解開通向星界大魔導士殿堂的終極星門，並獲得象徵最高榮譽的【星空守護之星 🌟】，請接受我的「英語問句三重試煉」！",
    rewardXP: 200,
    starName: "星空守護之星 🌟",
    victoryDialogue: "Magnificent! 你的英語問句宛如夜空中最璀璨的星光，發音自信流暢！以星象總監之名，我將這顆至高榮耀的【星空守護之星】授予你，你已正式通關雲頂星空觀測站，大魔導士殿堂的榮耀星門為你敞開！",
    questions: [
      {
        stage: 1,
        type: 'choice',
        title: '問句試煉 1/3：疑問詞選擇題 (Question Words)',
        scenario: '天象觀測情境：你仰望夜空，想向艾瑟爾賢者打聽今晚明月升起的時間',
        prompt: '請問句中的空格應填入哪一個疑問詞？',
        sentence: "“_____ does the bright moon rise tonight?”",
        sentenceZh: "「今晚明亮的月亮會在什麼時候升起？」",
        audioText: "When does the bright moon rise tonight?",
        options: [
          { key: 'A', text: 'When', correct: true, hint: '完全正確！詢問時間或時刻使用 When。' },
          { key: 'B', text: 'Where', correct: false, hint: 'Where 是詢問「地點」，這裡詢問的是時間喔！' },
          { key: 'C', text: 'Who', correct: false, hint: 'Who 是詢問「人物」，不能用來詢問天象時間喔！' },
          { key: 'D', text: 'Why', correct: false, hint: 'Why 是詢問「原因/為什麼」，詢問時間要用 When！' }
        ],
        explanation: '【When】用於詢問時間或何時發生。「When does the bright moon rise tonight?」意為「今晚明月何時升起？」。'
      },
      {
        stage: 2,
        type: 'choice',
        title: '問句試煉 2/3：情境助動詞選擇題 (Auxiliary Verbs)',
        scenario: '望遠鏡觀測情境：賢者調整好巨型望遠鏡鏡頭，詢問你是否能看見發光的星辰',
        prompt: '請問句中的空格應填入哪一個助動詞？',
        sentence: "“_____ you see the glowing star through the telescope?”",
        sentenceZh: "「你能透過望遠鏡看見那顆發光的星星嗎？」",
        audioText: "Can you see the glowing star through the telescope?",
        options: [
          { key: 'A', text: 'Can', correct: true, hint: '太優秀了！「Can you see...」是用於詢問能力與感官觀察最經典的問句！' },
          { key: 'B', text: 'Are', correct: false, hint: '主詞是 you 且搭配原形動詞 see，接 Are 會違反文法喔！' },
          { key: 'C', text: 'Do', correct: false, hint: 'Do you 一般用於日常習慣；詢問當下能否看見通常使用 Can。' },
          { key: 'D', text: 'Is', correct: false, hint: '主詞為 you，絕不能使用 Is 喔！' }
        ],
        explanation: '【Can】表示能力或感官觀察，「Can you see...?」是英語中詢問「你能看見...嗎？」最道地的問法。'
      },
      {
        stage: 3,
        type: 'speech',
        title: '終極試煉 3/3：英語問句口說朗讀 (Required Accuracy ≥ 80%)',
        scenario: '星空終極口說任務：請向艾瑟爾賢者清晰大聲朗讀經典問句，解開星界終極星門！',
        prompt: '請點擊下方麥克風，完整清晰地朗讀出這句英語問句：',
        targetSentence: "Can you see the bright star in the sky?",
        targetSentenceZh: "「你能看見天空中那顆明亮的星星嗎？」",
        phoneticGuide: "/kæn juː siː ðə braɪt stɑːr ɪn ðə skaɪ/",
        targetKeywords: ["can", "you", "see", "the", "bright", "star", "in", "the", "sky"],
        requiredAccuracy: 80,
        audioText: "Can you see the bright star in the sky?"
      }
    ]
  },
  'zone8': {
    zoneId: 'zone8',
    zoneName: '極光冰雪聖域',
    bossId: 'archmage_frost',
    bossName: '佛洛斯特長老 (Archmage Frost)',
    bossRole: '❄️ 極光雪境長老・冰霜大魔導士',
    bossAvatar: 'assets/textures/tex-clocktower-face.jpg',
    bossEmoji: '❄️',
    introDialogue: "Greetings, 頂風冒雪的尋星使者！我是極光冰雪聖域的守護者——佛洛斯特 ❄️。你已經成功跨越雲頂觀測站，抵達了大陸最高聳的極光冰封之巔。想要解開通向星界大魔導士殿堂的終極攀登冰階，並獲頒至高榮譽的【極光冰晶之星 ❄️】，請接受我的「英語問句三重試煉」！",
    rewardXP: 200,
    starName: "極光冰晶之星 ❄️",
    victoryDialogue: "Brilliant! 你的英語問句宛如極光般璀璨耀眼，發音清晰堅定！以冰霜大魔導士之名，我將這顆【極光冰晶之星】授予你。你已正式征服極光冰雪聖域，聖域之巔的攀登冰階為你全面解鎖，榮耀邁向星界大魔導士殿堂！",
    questions: [
      {
        stage: 1,
        type: 'choice',
        title: '問句試煉 1/3：天氣疑問詞選擇題 (Weather Questions)',
        scenario: '極地氣候情境：你裹緊防寒法袍，向佛洛斯特賢者詢問冬天這裡的天氣如何',
        prompt: '請問句中的空格應填入哪一個疑問詞？',
        sentence: "“_____ is the weather in winter?”",
        sentenceZh: "「冬天的天氣通常如何呢？」",
        audioText: "How is the weather in winter?",
        options: [
          { key: 'A', text: 'How', correct: true, hint: '完全正確！「How is the weather?」是英語中詢問天氣最經典標準的問句！' },
          { key: 'B', text: 'Who', correct: false, hint: 'Who 是詢問「人物/誰」，不能用來詢問天氣狀況喔！' },
          { key: 'C', text: 'Where', correct: false, hint: 'Where 是詢問「地點/在哪裡」，詢問天氣如何要用 How！' },
          { key: 'D', text: 'Why', correct: false, hint: 'Why 是詢問「原因/為什麼」，詢問天氣狀況請用 How！' }
        ],
        explanation: '【How】用於詢問狀態或狀況。「How is the weather?」意為「天氣如何？」，可搭配季節如「in winter」詢問冬天氣候。'
      },
      {
        stage: 2,
        type: 'choice',
        title: '問句試煉 2/3：情境助動詞/Be動詞選擇題 (Auxiliary & Be Verbs)',
        scenario: '雪峰觀測情境：賢者望著漫天飛舞的白雪，詢問你今天聖域是否非常寒冷且在下雪',
        prompt: '請問句中的空格應填入哪一個動詞？',
        sentence: "“_____ it cold and snowy today?”",
        sentenceZh: "「今天天氣寒冷而且在下雪嗎？」",
        audioText: "Is it cold and snowy today?",
        options: [
          { key: 'A', text: 'Is', correct: true, hint: '太優秀了！天氣虛主詞 it 在現在式疑問句中搭配 Be 動詞 Is。' },
          { key: 'B', text: 'Do', correct: false, hint: '主詞 it 後接形容詞 cold，不可使用 Do，必須使用 Be 動詞！' },
          { key: 'C', text: 'Are', correct: false, hint: '主詞 it 為單數第三人稱，不可搭配複數 Are 喔！' },
          { key: 'D', text: 'Can', correct: false, hint: '詢問當天天氣狀態通常使用「Is it cold...?」而非 Can it cold。' }
        ],
        explanation: '【Is】搭配天氣虛主詞 it，「Is it cold and snowy today?」是用於確認當天天氣狀態最道地的問法。'
      },
      {
        stage: 3,
        type: 'speech',
        title: '終極試煉 3/3：英語問句口說朗讀 (Required Accuracy ≥ 80%)',
        scenario: '雪山極限口說任務：請向佛洛斯特長老清晰大聲朗讀攀登問句，解開聖域終極攀登冰階！',
        prompt: '請點擊下方麥克風，完整清晰地朗讀出這句英語問句：',
        targetSentence: "Can you climb the white snow mountain?",
        targetSentenceZh: "「你能攀登這座白雪皚皚的高山嗎？」",
        phoneticGuide: "/kæn juː klaɪm ðə waɪt snoʊ ˈmaʊntən/",
        targetKeywords: ["can", "you", "climb", "the", "white", "snow", "mountain"],
        requiredAccuracy: 80,
        audioText: "Can you climb the white snow mountain?"
      }
    ]
  },
  'zone9': {
    zoneId: 'zone9',
    zoneName: '星界萬神殿堂',
    bossId: 'grand_archmage_oliver',
    bossName: '奧利弗大校長 (Grand Archmage Oliver)',
    bossRole: '🏛️ 星界大導師・智慧萬神殿長老',
    bossAvatar: 'assets/textures/owl-guide.png',
    bossEmoji: '🏛️',
    introDialogue: "Salutations, 卓越的年輕冒險者！我是萬神殿堂大導師——奧利弗 🏛️。你走過了書齋、市集、森林、操場、車站、海港、觀測站與冰雪聖域，終於登上了象徵宇宙智慧殿堂的萬神之巔！想要通過最後的考驗、榮獲至高無上的【星界智慧之星 🌟】，請接受我的「英語問句三重終極試煉」！",
    rewardXP: 300,
    starName: "星界智慧之星 🌟",
    victoryDialogue: "Magnificent! 你的思維敏捷、發音鏗鏘有力，完美詮釋了求知與智慧的真正真諦！以星界萬神殿堂大導師之名，我將【星界智慧之星】頒發給你！恭喜你圓滿通關全 9 大空間，榮耀加冕為全領域英語大魔導士！",
    questions: [
      {
        stage: 1,
        type: 'choice',
        title: '問句試煉 1/3：數量疑問詞選擇題 (Quantity Question Words)',
        scenario: '大圖書館探索情境：奧利弗大校長詢問你在這座宏偉的萬神圖書館中讀了多少本書',
        prompt: '請問句中的空格應填入哪一個疑問詞？',
        sentence: "“_____ many books do you read in the library?”",
        sentenceZh: "「你在這座圖書館裡讀了多少本書呢？」",
        audioText: "How many books do you read in the library?",
        options: [
          { key: 'A', text: 'How', correct: true, hint: '答對了！「How many」是用於詢問可數名詞數量的標準英語問句開頭！' },
          { key: 'B', text: 'What', correct: false, hint: 'What many 是不合文法的組合，詢問數量要用 How many 喔！' },
          { key: 'C', text: 'Where', correct: false, hint: 'Where 是詢問地點，詢問多少本要搭配 How many！' },
          { key: 'D', text: 'Who', correct: false, hint: 'Who 是詢問人物，不能與 many books 搭配詢問數量喔！' }
        ],
        explanation: '【How】搭配 many（How many + 複數名詞）用於詢問數量。「How many books do you read in the library?」為最常見的閱讀數量問句。'
      },
      {
        stage: 2,
        type: 'choice',
        title: '問句試煉 2/3：情境能力助動詞選擇題 (Modal Auxiliary Verbs)',
        scenario: '星界展翅情境：大導師指著殿堂外浩瀚的繁星雲海，問你我們能否在星空中展翅高飛',
        prompt: '請問句中的空格應填入哪一個助動詞？',
        sentence: "“_____ we fly high in the starry sky?”",
        sentenceZh: "「我們能在這片繁星閃爍的天空中高飛嗎？」",
        audioText: "Can we fly high in the starry sky?",
        options: [
          { key: 'A', text: 'Can', correct: true, hint: '太優秀了！「Can we fly...」表示詢問能力或提議「我們能...飛翔嗎？」。' },
          { key: 'B', text: 'Are', correct: false, hint: '搭配原形動詞 fly，不能使用 Be 動詞 Are 喔！' },
          { key: 'C', text: 'Is', correct: false, hint: '主詞是複數 we，絕對不能使用單數 Is！' },
          { key: 'D', text: 'Do', correct: false, hint: '詢問展翅飛翔的能力與可能性，以助動詞 Can 最為貼切！' }
        ],
        explanation: '【Can】表示能力與可能性，「Can we fly high in the starry sky?」意思為「我們能在繁星璀璨的夜空中翱翔高飛嗎？」。'
      },
      {
        stage: 3,
        type: 'speech',
        title: '終極試煉 3/3：英語整句口說朗讀 (Required Accuracy ≥ 80%)',
        scenario: '智慧加冕任務：請向奧利弗大導師大聲朗讀出這句智慧箴言，加冕為星界大魔導士！',
        prompt: '請點擊下方麥克風，完整清晰地朗讀出這句智慧誓言：',
        targetSentence: "I can read and think to be smart.",
        targetSentenceZh: "「我能透過閱讀與思考變得聰明智慧。」",
        phoneticGuide: "/aɪ kæn riːd ænd θɪŋk tuː biː smɑːrt/",
        targetKeywords: ["i", "can", "read", "and", "think", "to", "be", "smart"],
        requiredAccuracy: 80,
        audioText: "I can read and think to be smart."
      }
    ]
  },
  'zone10': {
    zoneId: 'zone10',
    zoneName: '蒼穹虹光空島',
    bossId: 'boss_aria',
    bossName: '艾莉雅 (Aria, Queen of Rainbow Skies)',
    bossRole: '🌈 蒼穹彩虹之主・天籟精靈使',
    bossAvatar: 'assets/textures/owl-guide.png',
    bossEmoji: '🧝‍♀️',
    introDialogue: "Greetings, 天空與星界的傳奇旅人！我是蒼穹虹光空島的守護精靈使——艾莉雅 🧝‍♀️🌈。你歷經萬神殿堂的智慧洗禮，展開雙翼飛到了天際最神聖的虹彩仙境！在這裡，風聲成曲，彩虹為橋。想要獲得全境終極榮譽【虹彩夢想之星 🌈🌟】，請接受我的「英語問句三重天籟試煉」！",
    rewardXP: 350,
    starName: "虹彩夢想之星 🌈🌟",
    victoryDialogue: "Sublime! 你的心靈純淨如晴空、歌聲與發音如彩虹般繽紛動人！以蒼穹彩虹之主之名，我將這顆【虹彩夢想之星】授予你！你已走遍童趣王國的十座奇幻境域，正式加冕為「全境傳奇大魔導士」！",
    questions: [
      {
        stage: 1,
        type: 'choice',
        title: '問句試煉 1/3：感官聽力生活單字題 (Sensory Perception Questions)',
        scenario: '天籟空島情境：艾莉雅詢問你在這片純淨的空島天空中聽到了什麼美妙的聲音',
        prompt: '請問句中的空格應填入哪一個生活單字？',
        sentence: "“What do you hear in the sky? I hear sweet _____.”",
        sentenceZh: "「你在天空中聽到了什麼？我聽見了甜美的音樂。」",
        audioText: "What do you hear in the sky? I hear sweet music.",
        options: [
          { key: 'A', text: 'music', correct: true, hint: '太棒了！「sweet music」指美妙悅耳的音樂，完全符合天籟空島的旋律！' },
          { key: 'B', text: 'desk', correct: false, hint: 'desk 是書桌，不能搭配聽覺上的 sweet 喔！' },
          { key: 'C', text: 'pencil', correct: false, hint: 'pencil 是鉛筆，空中聽見的不是文具喔！' },
          { key: 'D', text: 'soup', correct: false, hint: 'soup 是熱湯，在天空中聆聽的是美妙的音樂喔！' }
        ],
        explanation: '【music】表示音樂，「I hear sweet music.」為在天空中聽見悠揚樂曲之標準日常表達。'
      },
      {
        stage: 2,
        type: 'choice',
        title: '問句試煉 2/3：自然天氣情境選擇題 (Weather & Nature Inquiries)',
        scenario: '七彩虹霓情境：艾莉雅指著雨後的蔚藍天空，請你指出橫跨在空島上的大自然奇觀',
        prompt: '請問句中的空格應填入哪一個天氣單字？',
        sentence: "“Look at the sky! After the rain, there is a beautiful _____.”",
        sentenceZh: "「看那天邊！雨過天晴後，出現了一道美麗的彩虹。」",
        audioText: "Look at the sky! After the rain, there is a beautiful rainbow.",
        options: [
          { key: 'A', text: 'rainbow', correct: true, hint: '答對了！雨過天晴後空中出現的七彩光弧就是「rainbow (彩虹)」！' },
          { key: 'B', text: 'eraser', correct: false, hint: 'eraser 是橡皮擦，大自然雨後出現的是彩虹喔！' },
          { key: 'C', text: 'tiger', correct: false, hint: 'tiger 是老虎，天空出現的壯觀景象是彩虹！' },
          { key: 'D', text: 'fork', correct: false, hint: 'fork 是叉子，請選擇象徵七彩天橋的 rainbow！' }
        ],
        explanation: '【rainbow】意為彩虹，「After the rain, there is a beautiful rainbow.」為雨過天晴出現美麗彩虹的生活表達。'
      },
      {
        stage: 3,
        type: 'speech',
        title: '終極試煉 3/3：英語整句口說朗讀 (Required Accuracy ≥ 80%)',
        scenario: '傳奇加冕任務：請向艾莉雅精靈使大聲朗讀出這句歡欣誓詞，榮耀加冕為傳奇大魔導士！',
        prompt: '請點擊下方麥克風，完整清晰地朗讀出這句彩虹誓詞：',
        targetSentence: "We sing and dance under the rainbow.",
        targetSentenceZh: "「我們在彩虹下唱歌與跳舞。」",
        phoneticGuide: "/wiː sɪŋ ænd dæns ˈʌn.dɚ ðə ˈreɪn.boʊ/",
        targetKeywords: ["we", "sing", "and", "dance", "under", "the", "rainbow"],
        requiredAccuracy: 80,
        audioText: "We sing and dance under the rainbow."
      }
    ]
  }
};
