// 國小英語單字與童趣森林導師資料庫 (VocabDatabase)
const VOCAB_DATA = {
  "LIGHT": {
    word: "LIGHT",
    phonics: "/laɪt/ • L-I-G-H-T",
    zh: "光芒、點亮",
    category: "幼苗村日常",
    mascot: "foxy",
    mascotName: "小狐狸 Foxy",
    mascotImg: "assets/textures/fox-guide.png",
    dialogue: "“Look! A soft golden light dispels the morning shadows.”",
    dialogueZh: "「你看！柔和的金光驅散了清晨的陰影。」",
    prompt: "請看著銅燭台，大聲唸出：LIGHT！",
    puzzleHint: "找到古老的銅燭台，點燃它來照亮書桌角落！",
    audioFile: "assets/sounds/vocab/LIGHT.wav",
    matchKeywords: ["light", "lite", "lights", "like"],
    xp: 50,
    color: "#f6e05e"
  },
  "BOOK": {
    word: "BOOK",
    phonics: "/bʊk/ • B-O-O-K",
    zh: "書本、魔導書",
    category: "幼苗村日常",
    mascot: "foxy",
    mascotName: "小狐狸 Foxy",
    mascotImg: "assets/textures/fox-guide.png",
    dialogue: "“Open your book and discover the ancient magical words.”",
    dialogueZh: "「打開這本古老的魔導書，發現被遺忘的魔法。」",
    prompt: "請對著漂浮的古書，唸出：BOOK！",
    puzzleHint: "書桌上方的魔導書正在漂浮，裡面夾著重要之物！",
    audioFile: "assets/sounds/vocab/BOOK.wav",
    matchKeywords: ["book", "books", "look"],
    xp: 50,
    color: "#63b3ed"
  },
  "KEY": {
    word: "KEY",
    phonics: "/kiː/ • K-E-Y",
    zh: "鑰匙、關鍵",
    category: "重要道具",
    mascot: "foxy",
    mascotName: "小狐狸 Foxy",
    mascotImg: "assets/textures/fox-guide.png",
    dialogue: "“The golden key will open the locked drawer!”",
    dialogueZh: "「黃銅鑰匙能開啟緊閉的書桌抽屜！」",
    prompt: "請唸出鑰匙的真名：KEY！",
    puzzleHint: "鑰匙飄落到了桌上，用它打開抽屜！",
    audioFile: "assets/sounds/vocab/KEY.wav",
    matchKeywords: ["key", "keys", "keep", "ki"],
    xp: 50,
    color: "#ecc94b"
  },
  "RED": {
    word: "RED",
    phonics: "/red/ • R-E-D",
    zh: "紅色、火紅",
    category: "綠葉鎮魔藥",
    mascot: "bunny",
    mascotName: "小兔 Bunny",
    mascotImg: "assets/textures/rabbit-guide.png",
    dialogue: "“Red glows like a warm campfire in the forest!”",
    dialogueZh: "「紅色就像森林中溫暖的營火一樣閃閃發光！」",
    prompt: "請唸出火之魔藥的顏色：RED！",
    puzzleHint: "抽屜裡的火紅魔藥正是煉金星象儀所需的基底！",
    audioFile: "assets/sounds/vocab/RED.wav",
    matchKeywords: ["red", "read", "rad"],
    xp: 50,
    color: "#fc8181"
  },
  "BLUE": {
    word: "BLUE",
    phonics: "/bluː/ • B-L-U-E",
    zh: "藍色、蒼藍",
    category: "綠葉鎮魔藥",
    mascot: "bunny",
    mascotName: "小兔 Bunny",
    mascotImg: "assets/textures/rabbit-guide.png",
    dialogue: "“Blue is the color of the clear morning sky.”",
    dialogueZh: "「藍色是清晨晴空與清涼溪流的顏色。」",
    prompt: "請唸出水之魔藥的顏色：BLUE！",
    puzzleHint: "與 RED 藥水一起注入星象儀，喚醒星芒！",
    audioFile: "assets/sounds/vocab/BLUE.wav",
    matchKeywords: ["blue", "blew", "bloom"],
    xp: 50,
    color: "#63b3ed"
  },
  "STAR": {
    word: "STAR",
    phonics: "/stɑːr/ • S-T-A-R",
    zh: "星星、星芒",
    category: "星象秘寶",
    mascot: "bunny",
    mascotName: "小兔 Bunny",
    mascotImg: "assets/textures/rabbit-guide.png",
    dialogue: "“The bright star will guide us through the night!”",
    dialogueZh: "「明亮的星星為黑夜中的旅人指引方向！」",
    prompt: "請唸出天象儀中央閃耀的徽記：STAR！",
    puzzleHint: "調配好紅與藍藥水，星芒之石就會現身！",
    audioFile: "assets/sounds/vocab/STAR.wav",
    matchKeywords: ["star", "stars", "start"],
    xp: 70,
    color: "#f6e05e"
  },
  "CAT": {
    word: "CAT",
    phonics: "/kæt/ • C-A-T",
    zh: "貓咪",
    category: "奇幻生物",
    mascot: "mimic",
    mascotName: "貓咪寶箱怪 Mimic",
    mascotImg: "assets/textures/cute-cat-mimic.jpg",
    dialogue: "“Purr, purr... The sleepy chest with cat ears is hungry!”",
    dialogueZh: "「呼嚕呼嚕... 長著貓耳朵的小寶箱正在打盹，牠肚子餓了！」",
    prompt: "請唸出這隻可愛生物的名字：CAT！",
    puzzleHint: "角落的寶箱怪長著毛茸茸的耳朵，牠想吃新鮮的美食！",
    audioFile: "assets/sounds/vocab/CAT.wav",
    matchKeywords: ["cat", "cats", "cut"],
    xp: 50,
    color: "#ed8936"
  },
  "FISH": {
    word: "FISH",
    phonics: "/fɪʃ/ • F-I-S-H",
    zh: "魚、小魚乾",
    category: "森林美食",
    mascot: "mimic",
    mascotName: "貓咪寶箱怪 Mimic",
    mascotImg: "assets/textures/cute-cat-mimic.jpg",
    dialogue: "“Meow! A fresh fish is my favorite treat!”",
    dialogueZh: "「喵嗚！美味的小魚是我最愛的大餐！」",
    prompt: "請唸出貓咪寶箱最愛的食物：FISH！",
    puzzleHint: "把從星象台獲得的小魚乾餵給寶箱怪！",
    audioFile: "assets/sounds/vocab/FISH.wav",
    matchKeywords: ["fish", "fishes"],
    xp: 50,
    color: "#4fd1c5"
  },
  "DOOR": {
    word: "DOOR",
    phonics: "/dɔːr/ • D-O-O-R",
    zh: "大門、門扉",
    category: "大樹城遺跡",
    mascot: "ollie",
    mascotName: "貓頭鷹長老 Ollie",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Only wisdom may unlock this ancient stone door.”",
    dialogueZh: "「唯有知曉話語的真名，方能開啟遠古石門。」",
    prompt: "請唸出通往森林的出口：DOOR！",
    puzzleHint: "石門需要嵌入 STAR 與 FLOWER 魔法石！",
    audioFile: "assets/sounds/vocab/DOOR.wav",
    matchKeywords: ["door", "doors"],
    xp: 60,
    color: "#b7791f"
  },
  "FLOWER": {
    word: "FLOWER",
    phonics: "/ˈflaʊ.ər/ • F-L-O-W-E-R",
    zh: "花朵、蒼月草",
    category: "奇幻傳奇",
    mascot: "ollie",
    mascotName: "貓頭鷹長老 Ollie",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“The legendary blue flower blooms across the peaceful meadow.”",
    dialogueZh: "「傳說中的蒼月之花，正盛開在門外的整片花田上。」",
    prompt: "請唸出傳奇之花的名稱：FLOWER！",
    puzzleHint: "寶箱怪吐出的蒼月花石刻，是解開封印的關鍵！",
    audioFile: "assets/sounds/vocab/FLOWER.wav",
    matchKeywords: ["flower", "flowers", "flour"],
    xp: 80,
    color: "#63b3ed"
  },
  "OPEN": {
    word: "OPEN",
    phonics: "/ˈoʊ.pən/ • O-P-E-N",
    zh: "打開、開啟",
    category: "開門咒語",
    mascot: "ollie",
    mascotName: "貓頭鷹長老 Ollie",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Chant the spell: OPEN, and your new journey shall begin!”",
    dialogueZh: "「大聲詠唱解除封印的咒語：OPEN，迎向朝陽與花田吧！」",
    prompt: "請大聲詠唱開門真名：OPEN！",
    puzzleHint: "嵌入兩顆魔法石後，大聲唸出 OPEN 開啟石門！",
    audioFile: "assets/sounds/vocab/OPEN.wav",
    matchKeywords: ["open", "opened", "hoping"],
    xp: 70,
    color: "#48bb78"
  },
  "SUN": {
    word: "SUN",
    phonics: "/sʌn/ • S-U-N",
    zh: "太陽、朝陽",
    category: "自然天地",
    mascot: "ollie",
    mascotName: "貓頭鷹長老 Ollie",
    mascotImg: "assets/textures/owl-guide.png",
    dialogue: "“Warm sun shines on our peaceful Whimsy Forest.”",
    dialogueZh: "「溫暖燦爛的朝陽，正照耀著和平的童趣森林。」",
    prompt: "推開門迎向陽光，唸出：SUN！",
    puzzleHint: "走出石門，步入陽光燦爛的花田！",
    audioFile: "assets/sounds/vocab/SUN.wav",
    matchKeywords: ["sun", "son", "sunny"],
    xp: 50,
    color: "#f6ad55"
  },
  "SHIP": {
    word: "SHIP",
    phonics: "/ʃɪp/ • S-H-I-P",
    zh: "大帆船、輪船",
    category: "蔚藍秘境海港",
    mascot: "marina",
    mascotName: "瑪琳娜船長 Marina",
    mascotImg: "assets/textures/tex-town-facade.jpg",
    dialogue: "“The majestic galleon ship is ready to set sail across the ocean!”",
    dialogueZh: "「威風凜凜的三桅大帆船已備妥風帆，準備啟航橫越大洋！」",
    prompt: "請看著碼頭旁停泊的宏偉帆船，唸出：SHIP！",
    puzzleHint: "碼頭停泊著巨大的三桅遠洋帆船，登上甲板感受航海的壯麗！",
    audioFile: "assets/sounds/vocab/SHIP.wav",
    matchKeywords: ["ship", "ships", "sheep"],
    xp: 60,
    color: "#0284c7"
  },
  "BOAT": {
    word: "BOAT",
    phonics: "/boʊt/ • B-O-A-T",
    zh: "小艇、小木船",
    category: "蔚藍秘境海港",
    mascot: "marina",
    mascotName: "瑪琳娜船長 Marina",
    mascotImg: "assets/textures/tex-town-facade.jpg",
    dialogue: "“The wooden boat rocks gently beside the harbor pier.”",
    dialogueZh: "「繫在碼頭邊的木造小艇隨著海浪輕輕搖曳晃動。」",
    prompt: "請看著碼頭繫纜樁旁的小船，唸出：BOAT！",
    puzzleHint: "港口木棧道邊繫著一艘輕巧的小木艇，是近海探險的良伴！",
    audioFile: "assets/sounds/vocab/BOAT.wav",
    matchKeywords: ["boat", "boats", "bolt"],
    xp: 50,
    color: "#f59e0b"
  },
  "WIND": {
    word: "WIND",
    phonics: "/wɪnd/ • W-I-N-D",
    zh: "微風、航海之風",
    category: "蔚藍秘境海港",
    mascot: "marina",
    mascotName: "瑪琳娜船長 Marina",
    mascotImg: "assets/textures/tex-town-facade.jpg",
    dialogue: "“A brisk ocean wind fills the sails and turns the lighthouse vane!”",
    dialogueZh: "「強勁清爽的海風吹鼓了風帆，也轉動了燈塔上的航海風向標！」",
    prompt: "請感受吹拂海面的清爽微風，唸出：WIND！",
    puzzleHint: "燈塔頂端的風向標與風向旗正隨風旋轉，為水手測量風向！",
    audioFile: "assets/sounds/vocab/WIND.wav",
    matchKeywords: ["wind", "winds", "win", "wing"],
    xp: 50,
    color: "#38bdf8"
  },
  "WATER": {
    word: "WATER",
    phonics: "/ˈwɔː.tər/ • W-A-T-E-R",
    zh: "海水、碧波清泉",
    category: "蔚藍秘境海港",
    mascot: "marina",
    mascotName: "瑪琳娜船長 Marina",
    mascotImg: "assets/textures/tex-town-facade.jpg",
    dialogue: "“The crystal clear blue water sparkles under the warm morning sunlight.”",
    dialogueZh: "「澄澈湛藍的港灣海水在晨曦朝陽下閃爍著點點波光。」",
    prompt: "請俯瞰碼頭邊清澈碧藍的海水，唸出：WATER！",
    puzzleHint: "碼頭觀景台邊的海水碧藍透亮，波光粼粼！",
    audioFile: "assets/sounds/vocab/WATER.wav",
    matchKeywords: ["water", "waters", "waiter"],
    xp: 50,
    color: "#06b6d4"
  },
  "MOON": {
    word: "MOON",
    phonics: "/muːn/ • M-O-O-N",
    zh: "月亮、蒼月",
    category: "雲頂星空觀測站",
    mascot: "aethel",
    mascotName: "艾瑟爾賢者 Aethel",
    mascotImg: "assets/textures/tex-clocktower-face.jpg",
    dialogue: "“Look up! The silvery crescent moon watches over our magical academy.”",
    dialogueZh: "「抬頭看！銀白色的弦月正在雲頂天幕守護著我們的魔法學院。」",
    prompt: "請看著觀測站的蒼月潮汐日晷儀，唸出：MOON！",
    puzzleHint: "觀測站中央的潮汐日晷正隨著月相緩緩旋轉，散發出銀藍光芒！",
    audioFile: "assets/sounds/vocab/MOON.wav",
    matchKeywords: ["moon", "moons", "mood"],
    xp: 60,
    color: "#93c5fd"
  },
  "CLOUD": {
    word: "CLOUD",
    phonics: "/klaʊd/ • C-L-O-U-D",
    zh: "雲朵、雲海",
    category: "雲頂星空觀測站",
    mascot: "aethel",
    mascotName: "艾瑟爾賢者 Aethel",
    mascotImg: "assets/textures/tex-clocktower-face.jpg",
    dialogue: "“Fluffy white clouds float peacefully like an ocean beneath our feet.”",
    dialogueZh: "「綿密蓬鬆的白色雲朵就像腳下一望無際的雲海，靜靜飄動。」",
    prompt: "請俯瞰觀星露台邊緣起伏的雲海，唸出：CLOUD！",
    puzzleHint: "觀景浮台四周翻湧著純白的立體雲海，踩上去彷彿漫步空中！",
    audioFile: "assets/sounds/vocab/CLOUD.wav",
    matchKeywords: ["cloud", "clouds", "clown", "crowd"],
    xp: 50,
    color: "#e2e8f0"
  },
  "SKY": {
    word: "SKY",
    phonics: "/skaɪ/ • S-K-Y",
    zh: "天空、星空蒼穹",
    category: "雲頂星空觀測站",
    mascot: "aethel",
    mascotName: "艾瑟爾賢者 Aethel",
    mascotImg: "assets/textures/tex-clocktower-face.jpg",
    dialogue: "“The endless night sky is filled with glowing stars and distant galaxies!”",
    dialogueZh: "「無垠的夜空蒼穹中點綴著閃耀的恆星與遙遠星系！」",
    prompt: "請透過巨型天文望遠鏡望向無垠夜空，唸出：SKY！",
    puzzleHint: "巨型折射望遠鏡正指向天頂星河，窺探浩瀚宇宙的奧秘！",
    audioFile: "assets/sounds/vocab/SKY.wav",
    matchKeywords: ["sky", "skies", "ski"],
    xp: 50,
    color: "#38bdf8"
  }
};

// 關卡主英語問句試煉題庫 (Guardian Question Trials Database)
// 每位關卡主具備：
// 1. NPC 開場對話
// 2. 兩道英語問句填充選擇題 (Multiple Choice)
// 3. 一道高階英語問句朗讀挑戰 (Sentence Speech Trial, 正確率 >= 80%)
const GUARDIAN_TRIALS = {
  'zone6': {
    zoneId: 'zone6',
    zoneName: '蔚藍秘境海港',
    bossId: 'captain_marina',
    bossName: '瑪琳娜船長 (Captain Marina)',
    bossRole: '⚓ 皇家海港總督・傳奇領航者',
    bossAvatar: 'assets/textures/tex-town-facade.jpg',
    bossEmoji: '⚓',
    introDialogue: "Ahoy! 勇敢的冒險者！你已經掌握了海港的所有基礎字彙。但是，想要拿到航向未知海域的通行證並獲得本關卡【海港守護之星】，你必須通過我的「英語問句三重試煉」！拔錨啟航，接受挑戰吧！",
    rewardXP: 200,
    starName: "海港守護之星 ⚓",
    victoryDialogue: "Bravo! 你的英語問句掌握得無懈可擊，發音精準有力！以皇家海港總督之名，我將這顆【海港守護之星】授予你，浩瀚的星海航道已為你敞開！",
    questions: [
      {
        stage: 1,
        type: 'choice',
        title: '問句試煉 1/3：疑問詞選擇題 (Question Words)',
        scenario: '航海探索情境：你在碼頭想打聽遠洋帆船的航行方向',
        prompt: '請問句中的空格應填入哪一個疑問詞？',
        sentence: "“_____ is the big ship sailing to?”",
        sentenceZh: "「這艘大帆船要航向哪裡？」",
        audioText: "Where is the big ship sailing to?",
        options: [
          { key: 'A', text: 'Where', correct: true, hint: '答對了！詢問「地點/目的地」使用 Where。' },
          { key: 'B', text: 'When', correct: false, hint: 'When 是詢問「時間」，這裡詢問的是航向哪裡喔！' },
          { key: 'C', text: 'Who', correct: false, hint: 'Who 是詢問「人物」，不能用來問航行目的地喔！' },
          { key: 'D', text: 'What', correct: false, hint: '詢問航向某個目的地，以「Where ... sailing to?」最道地！' }
        ],
        explanation: '【Where】用於詢問地點、場所與目的地。「Where is the big ship sailing to?」意思為「這艘大帆船要航向何處？」。'
      },
      {
        stage: 2,
        type: 'choice',
        title: '問句試煉 2/3：情境助動詞選擇題 (Auxiliary Verbs)',
        scenario: '航海導航情境：船長指著遠方海平面的燈塔光芒詢問隊員',
        prompt: '請問句中的空格應填入哪一個助動詞？',
        sentence: "“_____ you see the lighthouse beam across the sea?”",
        sentenceZh: "「你能看見橫越海面的燈塔光束嗎？」",
        audioText: "Can you see the lighthouse beam across the sea?",
        options: [
          { key: 'A', text: 'Can', correct: true, hint: '太厲害了！Can you see... 用於詢問「你能看見...嗎？」。' },
          { key: 'B', text: 'Is', correct: false, hint: '主詞是 you 且搭配動詞原形 see，不能使用 Is 喔！' },
          { key: 'C', text: 'Does', correct: false, hint: '主詞是 you，一般動詞現在式疑問要用 Do 而非 Does。' },
          { key: 'D', text: 'Are', correct: false, hint: 'Are you 後方需接 V-ing 或形容詞，接原形動詞 see 需使用 Can。' }
        ],
        explanation: '【Can】表示能力或感官觀察，「Can you see...?」為生活與航海中最常用的詢問句：「你能看見...嗎？」。'
      },
      {
        stage: 3,
        type: 'speech',
        title: '終極試煉 3/3：英語問句口說朗讀 (Required Accuracy ≥ 80%)',
        scenario: '海港尋路任務：請用清晰標準的英語問句，向海港水手詢問燈塔的方位！',
        prompt: '請點擊下方麥克風，完整清晰地朗讀出這句英語問句：',
        targetSentence: "Where is the harbor lighthouse?",
        targetSentenceZh: "「請問海港燈塔在哪裡？」",
        phoneticGuide: "/wɛər ɪz ðə ˈhɑːrbər ˈlaɪtˌhaʊs/",
        targetKeywords: ["where", "is", "the", "harbor", "lighthouse"],
        requiredAccuracy: 80,
        audioText: "Where is the harbor lighthouse?"
      }
    ]
  },
  'zone1': {
    zoneId: 'zone1',
    zoneName: '見習學徒書齋',
    bossId: 'elder_ollie',
    bossName: '貓頭鷹長老 Ollie (Elder Ollie)',
    bossRole: '🦉 智慧殿堂守護者・貓頭鷹長老',
    bossAvatar: 'assets/textures/owl-guide.png',
    bossEmoji: '🦉',
    introDialogue: "咕咕！年輕的魔法學徒，你在書齋中的學習非常出色。不過，真正的大學者必須能夠靈活使用英語問句發問！來吧，通過我的問句三重考驗，奪取【書齋守護之星】！",
    rewardXP: 150,
    starName: "書齋守護之星 📜",
    victoryDialogue: "智慧的光芒在你眼中閃耀！你的英語問句精準無誤，這是屬於你的【書齋守護之星】！",
    questions: [
      {
        stage: 1,
        type: 'choice',
        title: '問句試煉 1/3：疑問詞選擇題 (Question Words)',
        scenario: '書齋探秘情境：你想知道桌上這本古老魔導書的名稱或內容',
        prompt: '請問句中的空格應填入哪一個疑問詞？',
        sentence: "“_____ is this magic book about?”",
        sentenceZh: "「這本魔法書是關於什麼的？」",
        audioText: "What is this magic book about?",
        options: [
          { key: 'A', text: 'What', correct: true, hint: '正確！詢問「事物內容」使用 What。' },
          { key: 'B', text: 'Where', correct: false, hint: 'Where 是詢問「地點」，詢問內容要用 What。' },
          { key: 'C', text: 'Who', correct: false, hint: 'Who 是詢問「人物」喔！' },
          { key: 'D', text: 'When', correct: false, hint: 'When 是詢問「時間」喔！' }
        ],
        explanation: '【What】用於詢問事物內容，「What is this magic book about?」意為「這本魔法書是關於什麼的？」。'
      },
      {
        stage: 2,
        type: 'choice',
        title: '問句試煉 2/3：位置問句選擇題 (Where & Prepositions)',
        scenario: '尋找關鍵道具：你在書齋中尋找打開抽屜的黃金鑰匙',
        prompt: '請問句中的空格應填入哪一個疑問詞？',
        sentence: "“_____ is the golden key on the desk?”",
        sentenceZh: "「書桌上的那把黃金鑰匙在哪裡？」",
        audioText: "Where is the golden key on the desk?",
        options: [
          { key: 'A', text: 'Where', correct: true, hint: '太棒了！詢問「在哪裡」要用 Where！' },
          { key: 'B', text: 'How', correct: false, hint: 'How 是詢問「如何/方式」喔。' },
          { key: 'C', text: 'Why', correct: false, hint: 'Why 是詢問「原因」喔。' },
          { key: 'D', text: 'Which', correct: false, hint: '這裡已明確指特定金鑰匙，詢問位置用 Where 最合適。' }
        ],
        explanation: '【Where】用於詢問位置或場所，「Where is the golden key on the desk?」意為「書桌上的黃金鑰匙在哪裡？」。'
      },
      {
        stage: 3,
        type: 'speech',
        title: '終極試煉 3/3：英語問句口說朗讀 (Required Accuracy ≥ 80%)',
        scenario: '書齋問答挑戰：請清晰標準朗讀出詢問光芒與燭台的問句！',
        prompt: '請點擊下方麥克風，完整清晰地朗讀出這句英語問句：',
        targetSentence: "Can you see the golden light?",
        targetSentenceZh: "「你能看見那道金色光芒嗎？」",
        phoneticGuide: "/kæn juː siː ðə ˈɡoʊldən laɪt/",
        targetKeywords: ["can", "you", "see", "the", "golden", "light"],
        requiredAccuracy: 80,
        audioText: "Can you see the golden light?"
      }
    ]
  },
  'zone7': {
    zoneId: 'zone7',
    zoneName: '雲頂星空觀測站',
    bossId: 'astrologer_aethel',
    bossName: '艾瑟爾賢者 (Astrologer Aethel)',
    bossRole: '🔭 星象總監・蒼穹觀星大師',
    bossAvatar: 'assets/textures/tex-clocktower-face.jpg',
    bossEmoji: '🔭',
    introDialogue: "Greetings, 年輕的尋星使者！我是雲頂星空觀測站的守護者——艾瑟爾 🔭。你已經攀登至學院最高的蒼穹之巔，掌握了星空的核心詞彙。想要解開通向星界大魔導士殿堂的終極星門，並獲得象徵最高榮譽的【星空守護之星 🌟】，請接受我的「英語問句三重試煉」！",
    rewardXP: 200,
    starName: "星空守護之星 🌟",
    victoryDialogue: "Magnificent! 你的英語問句宛如夜空中最璀璨的星光，發音自信流暢！以星象總監之名，我將這顆至高榮耀的【星空守護之星】授予你，你已正式通關雲頂星空觀測站，大魔導士殿堂的榮耀星門為你敞開！",
    questions: [
      {
        stage: 1,
        type: 'choice',
        title: '問句試煉 1/3：疑問詞選擇題 (Question Words)',
        scenario: '天象觀測情境：你仰望夜空，想向艾瑟爾賢者打聽今晚明月升起的時間',
        prompt: '請問句中的空格應填入哪一個疑問詞？',
        sentence: "“_____ does the bright moon rise tonight?”",
        sentenceZh: "「今晚明亮的月亮會在什麼時候升起？」",
        audioText: "When does the bright moon rise tonight?",
        options: [
          { key: 'A', text: 'When', correct: true, hint: '完全正確！詢問時間或時刻使用 When。' },
          { key: 'B', text: 'Where', correct: false, hint: 'Where 是詢問「地點」，這裡詢問的是時間喔！' },
          { key: 'C', text: 'Who', correct: false, hint: 'Who 是詢問「人物」，不能用來詢問天象時間喔！' },
          { key: 'D', text: 'Why', correct: false, hint: 'Why 是詢問「原因/為什麼」，詢問時間要用 When！' }
        ],
        explanation: '【When】用於詢問時間或何時發生。「When does the bright moon rise tonight?」意為「今晚明月何時升起？」。'
      },
      {
        stage: 2,
        type: 'choice',
        title: '問句試煉 2/3：情境助動詞選擇題 (Auxiliary Verbs)',
        scenario: '望遠鏡觀測情境：賢者調整好巨型望遠鏡鏡頭，詢問你是否能看見發光的星辰',
        prompt: '請問句中的空格應填入哪一個助動詞？',
        sentence: "“_____ you see the glowing star through the telescope?”",
        sentenceZh: "「你能透過望遠鏡看見那顆發光的星星嗎？」",
        audioText: "Can you see the glowing star through the telescope?",
        options: [
          { key: 'A', text: 'Can', correct: true, hint: '太優秀了！「Can you see...」是用於詢問能力與感官觀察最經典的問句！' },
          { key: 'B', text: 'Are', correct: false, hint: '主詞是 you 且搭配原形動詞 see，接 Are 會違反文法喔！' },
          { key: 'C', text: 'Do', correct: false, hint: 'Do you 一般用於日常習慣；詢問當下能否看見通常使用 Can。' },
          { key: 'D', text: 'Is', correct: false, hint: '主詞為 you，絕不能使用 Is 喔！' }
        ],
        explanation: '【Can】表示能力或感官觀察，「Can you see...?」是英語中詢問「你能看見...嗎？」最道地的問法。'
      },
      {
        stage: 3,
        type: 'speech',
        title: '終極試煉 3/3：英語問句口說朗讀 (Required Accuracy ≥ 80%)',
        scenario: '星空終極口說任務：請向艾瑟爾賢者清晰大聲朗讀經典問句，解開星界終極星門！',
        prompt: '請點擊下方麥克風，完整清晰地朗讀出這句英語問句：',
        targetSentence: "Can you see the bright star in the sky?",
        targetSentenceZh: "「你能看見天空中那顆明亮的星星嗎？」",
        phoneticGuide: "/kæn juː siː ðə braɪt stɑːr ɪn ðə skaɪ/",
        targetKeywords: ["can", "you", "see", "the", "bright", "star", "in", "the", "sky"],
        requiredAccuracy: 80,
        audioText: "Can you see the bright star in the sky?"
      }
    ]
  }
};
