// GENERATED by scripts/build-gas-schema.cjs. Do not edit independently.
/* Realm-specific mechanisms. Puzzle actions never write grades or award XP. */
(function(root){
  'use strict';
  const specs={
    zone2:{title:'市集採買：四枚金幣',english:'Two apples and one milk, please.',brief:'野餐清單：蘋果兩顆、牛奶一瓶。蘋果每顆 1 枚、牛奶每瓶 2 枚、麵包每個 2 枚。你有 4 枚金幣；裝好購物籃再結帳。',clues:['先看看清單上的食物數量與價格。','兩顆蘋果花 2 枚，一瓶牛奶花 2 枚；想想籃子裡要留下哪些食物。']},
    zone3:{title:'花園照護：三位小夥伴',english:'Water the tree. Feed the rabbit. Help the bird.',brief:'樹木缺水，小兔子想吃葉子，青鳥想吃種子。先選照護工具，再點選要幫忙的夥伴。',clues:['每位夥伴需要的東西不一樣。','水給 TREE，葉子給 RABBIT，種子給 BIRD；先選工具再選夥伴。']},
    zone4:{title:'運動接力：跨越終點',english:'Take the ball. Run, jump, then play soccer.',brief:'選好接力器材，再依跑道上的指示完成三個動作。不計時，可以慢慢看線索。',clues:['先選能踢的器材，再看英語動作順序。','需要 BALL；動作依序是 RUN、JUMP、SOCCER。']},
    zone5:{title:'車站解謎：準時上車',english:'The train leaves at eight thirty. Go to platform two.',brief:'車票寫著 08:30、月台 2。調整鐘面的時與分，選對月台再驗票。',clues:['車票的時間與月台必須同時符合。','Eight thirty 是 08:30，platform two 是月台 2。']},
    zone6:{title:'海港導航：避礁靠岸',english:'Sail to the lighthouse. Keep away from the rocks.',brief:'從左下方的小船出發，使用四個方向航行到右上方燈塔。礁石不能通過，岸邊也不能越界。',clues:['看看海圖中礁石的位置，找一條連續的水路。','先沿左側往北，到最上方後往東；船每次只移動一格。']},
    zone7:{title:'觀測站：對準東方月亮',english:'Find the moon in the east.',brief:'觀測筆記：東方的月亮是星門鑰匙。選擇天體，再轉動觀測儀；北 0°、東 90°、南 180°、西 270°。',clues:['筆記同時提到天體與方向。','選 MOON，把觀測儀轉到東方 90°，再確認對準。']},
    zone8:{title:'冰雪準備：溫暖出發',english:'Wear a coat, gloves and boots. Keep warm.',brief:'帶上外套、手套與雪靴。營火需要溫暖的 2 格熱度，太冷或太熱都不能出發。',clues:['裝備與營火都要準備好，才適合走進雪地。','留下外套、手套、雪靴，取消短褲與涼鞋；把熱度調到 2 格。']},
    zone9:{title:'智慧殿堂：修復故事卷軸',english:'Read first. Think next. Write last.',brief:'卷軸的步驟散開了。依英文線索把三張卡依序放回；放錯可以取回重排。',clues:['First、next、last 告訴你先後順序。','先 READ，再 THINK，最後 WRITE；排好後蓋上印章。']},
    zone10:{title:'虹光空島：奏響回家之歌',english:'Listen to the music. Sing the song.',brief:'彩虹琴譜：C → E → G → C。先聽四個音，再用琴鍵重現旋律，讓回家的虹橋亮起。',clues:['聽示範旋律，留意最後一個音與第一個音相同。','依序按 C、E、G、C；按錯可以清空琴譜重來。']}
  };
  const defaults={zone2:{cart:[0,0,0],paid:false},zone3:{tool:'WATER',care:[false,false,false]},zone4:{equipment:'',stage:0},zone5:{hour:6,minute:0,platform:1,boarded:false},zone6:{x:0,y:2},zone7:{object:'STAR',angle:0,aligned:false},zone8:{gear:[],heat:0,ready:false},zone9:{order:[],sealed:false},zone10:{notes:[],played:false}};
  const clone=x=>JSON.parse(JSON.stringify(x));
  const isInt=(x,a,b)=>Number.isInteger(x)&&x>=a&&x<=b;
  const eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
  function initial(id){return defaults[id]?clone(defaults[id]):null;}
  function solved(id,s){
    if(!s)return false;
    switch(id){
      case 'zone2':return s.paid===true&&eq(s.cart,[2,1,0]);
      case 'zone3':return eq(s.care,[true,true,true]);
      case 'zone4':return s.equipment==='BALL'&&s.stage===3;
      case 'zone5':return s.boarded===true&&s.hour===8&&s.minute===30&&s.platform===2;
      case 'zone6':return s.x===3&&s.y===0;
      case 'zone7':return s.aligned===true&&s.object==='MOON'&&s.angle===90;
      case 'zone8':return s.ready===true&&s.heat===2&&eq([...s.gear].sort(),['BOOTS','COAT','GLOVES']);
      case 'zone9':return s.sealed===true&&eq(s.order,['READ','THINK','WRITE']);
      case 'zone10':return s.played===true&&eq(s.notes,['C','E','G','C']);
      default:return false;
    }
  }
  function validateState(id,raw){
    if(!raw||!defaults[id])return null;
    let ok=false;
    switch(id){
      case 'zone2':ok=Array.isArray(raw.cart)&&raw.cart.length===3&&raw.cart.every(n=>isInt(n,0,3))&&typeof raw.paid==='boolean';break;
      case 'zone3':ok=['WATER','LEAF','SEEDS'].includes(raw.tool)&&Array.isArray(raw.care)&&raw.care.length===3&&raw.care.every(b=>typeof b==='boolean');break;
      case 'zone4':ok=['','BALL','BOOK','CLOCK'].includes(raw.equipment)&&isInt(raw.stage,0,3);break;
      case 'zone5':ok=[6,8,10].includes(raw.hour)&&[0,30,45].includes(raw.minute)&&isInt(raw.platform,1,3)&&typeof raw.boarded==='boolean';break;
      case 'zone6':ok=isInt(raw.x,0,3)&&isInt(raw.y,0,2)&&!((raw.x===1&&raw.y===1)||(raw.x===2&&raw.y===2));break;
      case 'zone7':ok=['STAR','MOON','SUN'].includes(raw.object)&&[0,90,180,270].includes(raw.angle)&&typeof raw.aligned==='boolean';break;
      case 'zone8':ok=Array.isArray(raw.gear)&&raw.gear.length<=5&&new Set(raw.gear).size===raw.gear.length&&raw.gear.every(g=>['COAT','GLOVES','BOOTS','SHORTS','SANDALS'].includes(g))&&isInt(raw.heat,0,3)&&typeof raw.ready==='boolean';break;
      case 'zone9':ok=Array.isArray(raw.order)&&raw.order.length<=3&&new Set(raw.order).size===raw.order.length&&raw.order.every(w=>['READ','THINK','WRITE'].includes(w))&&typeof raw.sealed==='boolean';break;
      case 'zone10':ok=Array.isArray(raw.notes)&&raw.notes.length<=4&&raw.notes.every(n=>['C','E','G'].includes(n))&&typeof raw.played==='boolean';break;
    }
    if(!ok)return null;
    const s=initial(id);for(const key of Object.keys(s))s[key]=clone(raw[key]);
    // A stale success flag cannot bypass a changed configuration.
    for(const key of ['paid','boarded','aligned','ready','sealed','played'])if(key in s&&!solved(id,s))s[key]=false;
    return s;
  }
  function sanitizeMap(map){const result={};if(!map||typeof map!=='object')return result;for(const id of Object.keys(defaults)){const state=validateState(id,map[id]);if(state)result[id]=state;}return result;}
  function transition(id,raw,action){
    const s=validateState(id,raw)||initial(id);if(!s||!action)return {state:s,message:'請先閱讀任務線索。'};
    if(solved(id,s))return {state:s,message:'任務已完成，可以回到秘境探索。'};
    let message='已更新，看看線索再試下一步。';
    switch(id){
      case 'zone2':
        if(action.type==='quantity'&&isInt(action.index,0,2)&&isInt(action.value,0,3))s.cart[action.index]=action.value;
        if(action.type==='pay'){s.paid=eq(s.cart,[2,1,0]);message=s.paid?'購物清單與 4 枚金幣剛好相符！':'還不能結帳：請核對食物數量與金幣總額。';}break;
      case 'zone3':
        if(action.type==='tool'&&['WATER','LEAF','SEEDS'].includes(action.value))s.tool=action.value;
        if(action.type==='care'&&isInt(action.index,0,2)){if(s.tool===['WATER','LEAF','SEEDS'][action.index]){s.care[action.index]=true;message='這位夥伴已經得到需要的照護！';}else message='這位夥伴需要別的東西；可以換一個工具再試。';}break;
      case 'zone4':
        if(action.type==='equipment'&&['BALL','BOOK','CLOCK'].includes(action.value)){s.equipment=action.value;s.stage=0;}
        if(action.type==='move'&&['RUN','JUMP','SOCCER'].includes(action.value)){if(s.equipment!=='BALL')message='接力還需要一顆球，先選器材。';else if(action.value===['RUN','JUMP','SOCCER'][s.stage]){s.stage++;message='完成第 '+s.stage+' 個動作！';}else {s.stage=0;message='順序有一點不同，再從 RUN 開始試試。';}}break;
      case 'zone5':
        if(action.type==='set'&&((action.key==='hour'&&[6,8,10].includes(action.value))||(action.key==='minute'&&[0,30,45].includes(action.value))||(action.key==='platform'&&isInt(action.value,1,3))))s[action.key]=action.value;
        if(action.type==='board'){s.boarded=s.hour===8&&s.minute===30&&s.platform===2;message=s.boarded?'時間與月台正確，車票驗證成功！':'時間或月台與車票不同，再看看車票。';}break;
      case 'zone6':{
        const delta={north:[0,-1],south:[0,1],west:[-1,0],east:[1,0]}[action.value];
        if(action.type==='sail'&&delta){const x=s.x+delta[0],y=s.y+delta[1];if(!isInt(x,0,3)||!isInt(y,0,2))message='岸邊不能通過，換個方向航行。';else if((x===1&&y===1)||(x===2&&y===2))message='前方有礁石，請找另一條水路。';else {s.x=x;s.y=y;message='已航行一格。';}}break;
      }
      case 'zone7':
        if(action.type==='object'&&['STAR','MOON','SUN'].includes(action.value))s.object=action.value;
        if(action.type==='rotate')s.angle=(s.angle+90)%360;
        if(action.type==='align'){s.aligned=s.object==='MOON'&&s.angle===90;message=s.aligned?'觀測儀已對準東方月亮！':'天體或方向與筆記不同，再觀察一次。';}break;
      case 'zone8':
        if(action.type==='gear'&&['COAT','GLOVES','BOOTS','SHORTS','SANDALS'].includes(action.value))s.gear=s.gear.includes(action.value)?s.gear.filter(g=>g!==action.value):[...s.gear,action.value];
        if(action.type==='heat'&&[-1,1].includes(action.value))s.heat=Math.min(3,Math.max(0,s.heat+action.value));
        if(action.type==='depart'){s.ready=s.heat===2&&eq([...s.gear].sort(),['BOOTS','COAT','GLOVES']);message=s.ready?'保暖裝備與營火都準備好了！':'請核對保暖裝備，並讓營火維持 2 格熱度。';}break;
      case 'zone9':
        if(action.type==='card'&&['READ','THINK','WRITE'].includes(action.value)&&!s.order.includes(action.value)&&s.order.length<3)s.order.push(action.value);
        if(action.type==='clear')s.order=[];
        if(action.type==='seal'){s.sealed=eq(s.order,['READ','THINK','WRITE']);message=s.sealed?'卷軸恢復了正確的故事步驟！':'順序與 first、next、last 不同，可以取回重排。';}break;
      case 'zone10':
        if(action.type==='note'&&['C','E','G'].includes(action.value)&&s.notes.length<4)s.notes.push(action.value);
        if(action.type==='clear')s.notes=[];
        if(action.type==='play'){s.played=eq(s.notes,['C','E','G','C']);message=s.played?'回家的旋律響起，虹橋亮了！':'旋律有一點不同，先聽示範再清空重彈。';}break;
    }
    return {state:s,message:solved(id,s)?'秘境任務完成！ '+message:message};
  }
  function canTravel(from,to,map,{restore=false,dev=false}={}){return restore||dev||!specs[from]||Number(to.slice(4))<=Number(from.slice(4))||solved(from,map?.[from]);}
  const api={specs,initial,solved,validateState,sanitizeMap,transition,canTravel};root.RealmQuests=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
/* Puzzle checkpoints are separate from the learning-record service. */
(function(root) {
  'use strict';
  const flags=['candleLit','bookOpened','hasKey','drawerOpened','hasRedPotion','hasBluePotion','alchemyMixed','hasStarStone','hasFish','catPracticed','mimicFed','hasFlowerStone','doorSocketsFilled','doorStonePlaced','doorOpened','escaped'];
  const number=(n,min,max)=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max;
  function ownerKey(profile,preview=false) {return preview?'preview':!profile||profile.isGuest?'guest':'student:'+String(profile.studentId||'').slice(0,100);}
  function validate(raw,owner,zones) {
    if(!raw||raw.version!==1||raw.owner!==owner||!zones[raw.zone]||!number(raw.savedAt,0,1e14))return null;
    const s=raw.state,p=raw.player;
    if(!s||!p||!number(s.xp,0,1000000)||!Array.isArray(s.inventory)||s.inventory.length>128)return null;
    if(!number(p.x,-1000,1000)||!number(p.z,-1000,1000)||!number(p.y,0,100)||!number(p.yaw,-1e6,1e6)||!number(p.pitch,-1.6,1.6))return null;
    const state={xp:Math.floor(s.xp),inventory:[],practicedWordsByZone:{},realmPuzzles:root.RealmQuests?.sanitizeMap(s.realmPuzzles)||{}};
    for(const key of flags){if(typeof s[key]!=='boolean')return null;state[key]=s[key];}
    const ids=new Set();
    for(const item of s.inventory){
      if(!item||typeof item.id!=='string'||!/^[A-Z0-9_]{1,48}$/.test(item.id)||typeof item.name!=='string'||item.name.length>80)return null;
      if(ids.has(item.id))continue;ids.add(item.id);
      state.inventory.push({id:item.id,name:item.name,color:typeof item.color==='string'&&/^#[0-9a-f]{3,8}$/i.test(item.color)?item.color:'#ecc94b'});
    }
    for(const [id,zone] of Object.entries(zones)){
      const list=s.practicedWordsByZone?.[id];
      if(Array.isArray(list))state.practicedWordsByZone[id]=[...new Set(list.filter(word=>zone.words.includes(word)))];
    }
    return {version:1,owner,zone:raw.zone,savedAt:raw.savedAt,state,player:{x:p.x,y:p.y,z:p.z,yaw:p.yaw,pitch:p.pitch}};
  }
  function capture(world,owner,now=Date.now()) {
    const state={xp:world.gameState.xp,inventory:world.gameState.inventory,practicedWordsByZone:world.gameState.practicedWordsByZone||{},realmPuzzles:world.gameState.realmPuzzles||{}};
    for(const key of flags)state[key]=world.gameState[key]===true;
    return {version:1,owner,zone:world.zoneManager.currentZoneId,savedAt:now,state,player:{x:world.player.pos.x,y:world.player.pos.y,z:world.player.pos.z,yaw:world.player.yaw,pitch:world.player.pitch}};
  }
  function applySavedPosition(player,saved,blocked) {
    if(!saved||!number(saved.x,-1000,1000)||!number(saved.z,-1000,1000)||!number(saved.yaw,-1e6,1e6)||!number(saved.pitch,-1.6,1.6)||blocked(saved.x,saved.z,player.radius))return false;
    player.pos.set(saved.x,1.6,saved.z);player.yaw=saved.yaw;player.pitch=saved.pitch;return true;
  }
  class CheckpointStore {
    constructor(storage,owner,zones){this.storage=storage;this.owner=owner;this.zones=zones;this.key='whimsy.adventure.v1:'+encodeURIComponent(owner);this.status='empty';this.savedAt=null;this.unreadable=null;}
    load(){
      try{
        const text=this.storage.getItem(this.key);if(!text){this.status='empty';return null;}
        let record=null;try{record=text.length<=256000?validate(JSON.parse(text),this.owner,this.zones):null;}catch(error){};
        if(!record){this.unreadable=text.slice(0,256000);this.status='invalid';return null;}
        this.savedAt=record.savedAt;this.status='saved';return record;
      }catch(error){this.status='unavailable';return null;}
    }
    save(snapshot){
      const record=validate(snapshot,this.owner,this.zones);if(!record){this.status='invalid';return false;}
      try{
        if(this.unreadable!==null){this.storage.setItem(this.key+':unreadable',this.unreadable);this.unreadable=null;}
        this.storage.setItem(this.key,JSON.stringify(record));this.savedAt=record.savedAt;this.status='saved';return true;
      }catch(error){this.status='unavailable';return false;}
    }
  }
  const api={flags,ownerKey,validate,capture,applySavedPosition,CheckpointStore};root.AdventureProgress=api;
  if(typeof module!=='undefined')module.exports=api;
})(globalThis);
var ADVENTURE_CHECKPOINT_ZONES={"zone1":{"id":"zone1","words":["LIGHT","BOOK","KEY","RED","BLUE","STAR","CAT","FISH","DOOR","FLOWER","OPEN","SUN"]},"zone2":{"id":"zone2","words":["APPLE","BANANA","BREAD","MILK","SWEET","OPEN"]},"zone3":{"id":"zone3","words":["RABBIT","BIRD","TREE","WATER","OPEN"]},"zone4":{"id":"zone4","words":["SOCCER","BALL","RUN","JUMP","OPEN"]},"zone5":{"id":"zone5","words":["TIME","CLOCK","TRAIN","MORNING","OPEN"]},"zone6":{"id":"zone6","words":["SHIP","BOAT","WIND","FISH","WATER","OPEN"]},"zone7":{"id":"zone7","words":["STAR","MOON","CLOUD","SUN","SKY","OPEN"]},"zone8":{"id":"zone8","words":["SNOW","COLD","WINTER","WHITE","WARM","CLIMB"]},"zone9":{"id":"zone9","words":["LIBRARY","READ","WRITE","THINK","SMART","FLY"]},"zone10":{"id":"zone10","words":["ISLAND","RAINBOW","MUSIC","SING","DANCE","DREAM"]}};
